# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2024-04-06T03:12:31+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Role(Enum):
    system = 'system'
    assistant = 'assistant'
    user = 'user'


class Message(BaseModel):
    role: Role = Field(..., title='Role')
    content: str = Field(..., title='Content')


class MessagesPayload(BaseModel):
    messages: List[Message] = Field(..., title='Messages')


class MessagesResponse(BaseModel):
    message: Message


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')
