apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "phoenix.postgres" . }}
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        ports:
        - containerPort: {{ .Values.database.port }}
          name: postgres
        env:
        - name: POSTGRES_DB
          value: {{ .Values.database.db }}
        - name: POSTGRES_USER
          value: {{ .Values.database.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.password }}
        resources: {{ toYaml .Values.postgres.resources | nindent 10 }} 
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ template "phoenix.postgres-pvc" . }}
