{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-{{ template "phoenix.service" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
  selector:
    app: postgres
{{- end }}
