import * as fsPromises from "node:fs/promises";
import * as path from "node:path";
import { Command } from "commander";

import { ExitCode, getExitCodeForError } from "../exitCodes";
import { writeError, writeOutput } from "../io";

const LLMS_TXT_URL = "https://arize.com/docs/phoenix/llms.txt";
const PHOENIX_DOCS_PREFIX = "https://arize.com/docs/phoenix/";
const DEFAULT_OUTPUT_DIR = ".px/docs";
const DEFAULT_WORKERS = 10;
const ALL_WORKFLOWS = "all";

export interface DocEntry {
  title: string;
  url: string;
  description: string;
  section: string;
}

interface DocsFetchOptions {
  workflow?: string[];
  outputDir: string;
  dryRun?: boolean;
  refresh?: boolean;
  strict?: boolean;
  workers: number;
}

/**
 * Maps user-facing workflow names to the top-level `##` section headings
 * in the llms.txt index. Entries under `###` subsections inherit their
 * parent `##` section.
 */
const WORKFLOW_SECTION_MAP: Record<string, string[]> = {
  tracing: ["tracing"],
  evaluation: ["evaluation"],
  datasets: ["datasets & experiments"],
  prompts: ["prompt engineering"],
  integrations: ["integrations"],
  sdk: ["sdk & api reference"],
  "self-hosting": ["self-hosting"],
};

const VALID_WORKFLOWS = Object.keys(WORKFLOW_SECTION_MAP);

/** The default set fetched when no --workflow is specified. */
const DEFAULT_WORKFLOWS = [
  "tracing",
  "evaluation",
  "datasets",
  "prompts",
  "integrations",
];

// ---------------------------------------------------------------------------
// Pure functions (exported for testing)
// ---------------------------------------------------------------------------

/**
 * Parse an llms.txt file into doc entries.
 *
 * The Phoenix llms.txt follows the llmstxt.org standard format:
 *   ## Section           — top-level sections
 *   ### Subsection       — subsections (inherit parent ## section)
 *   - [Title](url): Description
 */
export function parseLlmsTxt(content: string): DocEntry[] {
  const entries: DocEntry[] = [];
  let currentSection = "";

  for (const rawLine of content.split("\n")) {
    const line = rawLine.trim();

    // Track top-level ## section headings (subsections ### inherit the parent)
    const topSectionMatch = line.match(/^##\s+(?!#)(.+)/);
    if (topSectionMatch) {
      currentSection = topSectionMatch[1].trim();
      continue;
    }

    // Parse: - [Title](url): Description
    const entryMatch = line.match(
      /^-\s+\[([^\]]+)\]\((https?:\/\/[^)]+)\)(?::\s+(.*))?$/
    );
    if (entryMatch) {
      entries.push({
        title: entryMatch[1],
        url: entryMatch[2],
        description: entryMatch[3] ?? "",
        section: currentSection,
      });
    }
  }

  return entries;
}

/**
 * Filter doc entries by workflow categories. Returns all entries if
 * workflows is empty or contains ALL_WORKFLOWS.
 */
export function filterByWorkflows(
  entries: DocEntry[],
  workflows: string[]
): DocEntry[] {
  if (workflows.length === 0) {
    return entries;
  }

  const normalized = workflows.map((workflow) => workflow.toLowerCase());
  if (normalized.includes(ALL_WORKFLOWS)) {
    return entries;
  }

  const allowedSections = new Set<string>();
  for (const key of normalized) {
    const mapped = WORKFLOW_SECTION_MAP[key];
    if (mapped) {
      for (const section of mapped) {
        allowedSections.add(section);
      }
    }
  }

  return entries.filter((entry) =>
    allowedSections.has(entry.section.toLowerCase())
  );
}

/**
 * Convert a Phoenix docs URL to a local file path.
 * Strips the common prefix and appends `.md`.
 */
export function urlToFilePath(url: string, outputDir: string): string {
  let relative = url.startsWith(PHOENIX_DOCS_PREFIX)
    ? url.slice(PHOENIX_DOCS_PREFIX.length)
    : url;
  relative = relative.replace(/^\/+|\/+$/g, "");
  return path.join(outputDir, `${relative}.md`);
}

/**
 * Group doc entries by their section name (lowercased).
 */
export function groupBySection(entries: DocEntry[]): Map<string, DocEntry[]> {
  const groups = new Map<string, DocEntry[]>();
  for (const entry of entries) {
    const section = entry.section.toLowerCase();
    const group = groups.get(section);
    if (group) {
      group.push(entry);
    } else {
      groups.set(section, [entry]);
    }
  }
  return groups;
}

/**
 * Generate the content for the top-level README.md index file.
 */
export function generateReadme(
  entries: DocEntry[],
  grouped?: Map<string, DocEntry[]>
): string {
  const lines: string[] = [
    "# Phoenix Docs",
    "",
    "Generated by `px docs fetch`.",
    "",
  ];

  const sections = grouped ?? groupBySection(entries);
  for (const [section, sectionEntries] of sections) {
    lines.push(`## ${section}`);
    for (const entry of sectionEntries) {
      const filePath = urlToFilePath(entry.url, "").replace(/^\/+/, "");
      lines.push(`- [${entry.title}](${filePath})`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generate the content for a section-level _index.md file.
 * Uses paths relative to the section directory (derived from the first
 * entry's file path) so that links work from the _index.md location.
 */
export function generateSectionIndex(
  section: string,
  entries: DocEntry[]
): string {
  const lines: string[] = [`# ${section} Docs`, ""];

  // Determine the section directory from the first entry
  const firstFilePath = urlToFilePath(entries[0].url, "").replace(/^\/+/, "");
  const sectionDir = firstFilePath.split(path.sep)[0];

  for (const entry of entries) {
    const filePath = urlToFilePath(entry.url, "").replace(/^\/+/, "");
    // Strip the section directory prefix to get a relative path
    const relativePath = filePath.startsWith(sectionDir + path.sep)
      ? filePath.slice(sectionDir.length + 1)
      : filePath;
    lines.push(`- [${entry.title}](${relativePath})`);
    lines.push(`  source: \`${entry.url}.md\``);
  }

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Fetch helpers
// ---------------------------------------------------------------------------

async function fetchAndSave(entry: DocEntry, outputDir: string): Promise<void> {
  const markdownUrl = entry.url.endsWith(".md") ? entry.url : `${entry.url}.md`;
  const response = await fetch(markdownUrl);
  if (!response.ok) {
    throw new Error(`HTTP ${response.status} for ${markdownUrl}`);
  }
  const content = await response.text();
  const filePath = urlToFilePath(entry.url, outputDir);
  await fsPromises.mkdir(path.dirname(filePath), { recursive: true });
  await fsPromises.writeFile(filePath, content, "utf-8");
}

async function fetchWithConcurrency(
  entries: DocEntry[],
  outputDir: string,
  workers: number
): Promise<{
  succeeded: DocEntry[];
  failed: { entry: DocEntry; error: string }[];
}> {
  const succeeded: DocEntry[] = [];
  const failed: { entry: DocEntry; error: string }[] = [];

  for (let offset = 0; offset < entries.length; offset += workers) {
    const batch = entries.slice(offset, offset + workers);
    const results = await Promise.allSettled(
      batch.map((entry) => fetchAndSave(entry, outputDir).then(() => entry))
    );

    for (let index = 0; index < results.length; index++) {
      const result = results[index];
      if (result.status === "fulfilled") {
        succeeded.push(result.value);
      } else {
        failed.push({
          entry: batch[index],
          error:
            result.reason instanceof Error
              ? result.reason.message
              : String(result.reason),
        });
      }
    }
  }

  return { succeeded, failed };
}

/**
 * Write the README.md and per-section _index.md files.
 */
async function writeIndexFiles(
  entries: DocEntry[],
  outputDir: string
): Promise<void> {
  const grouped = groupBySection(entries);

  // Top-level README.md
  const readmeContent = generateReadme(entries, grouped);
  await fsPromises.writeFile(
    path.join(outputDir, "README.md"),
    readmeContent,
    "utf-8"
  );

  // Per-section _index.md files
  for (const [section, sectionEntries] of grouped) {
    const indexContent = generateSectionIndex(section, sectionEntries);
    // Derive the section directory from the first entry's file path
    const firstFilePath = urlToFilePath(sectionEntries[0].url, outputDir);
    const sectionDir = path.dirname(firstFilePath);
    await fsPromises.mkdir(sectionDir, { recursive: true });
    await fsPromises.writeFile(
      path.join(sectionDir, "_index.md"),
      indexContent,
      "utf-8"
    );
  }
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

function formatEntryLine(entry: DocEntry, target: string): string {
  const section = entry.section.toLowerCase();
  return `  - ${entry.title} [${section}] -> ${target}`;
}

async function docsFetchHandler(options: DocsFetchOptions): Promise<void> {
  // Fetch llms.txt index
  let response: Response;
  try {
    response = await fetch(LLMS_TXT_URL);
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Unknown error occurred";
    writeError({ message: `Error fetching llms.txt: ${message}` });
    process.exit(getExitCodeForError(error));
  }
  if (!response.ok) {
    writeError({
      message: `Failed to fetch llms.txt: HTTP ${response.status}`,
    });
    process.exit(ExitCode.NETWORK_ERROR);
  }
  writeOutput({ message: `Fetched docs index: ${LLMS_TXT_URL}` });
  const indexContent = await response.text();

  // Parse and filter
  let entries = parseLlmsTxt(indexContent);

  const workflows =
    options.workflow && options.workflow.length > 0
      ? options.workflow
      : DEFAULT_WORKFLOWS;

  for (const workflow of workflows) {
    const key = workflow.toLowerCase();
    if (key !== ALL_WORKFLOWS && !VALID_WORKFLOWS.includes(key)) {
      writeError({
        message: `Warning: unknown workflow "${workflow}". Valid values: ${VALID_WORKFLOWS.join(", ")}, all`,
      });
    }
  }
  entries = filterByWorkflows(entries, workflows);
  writeOutput({ message: `Workflows: ${workflows.join(", ")}` });

  if (entries.length === 0) {
    writeOutput({ message: "No matching pages found." });
    return;
  }

  // Dry run — show what would be fetched
  if (options.dryRun) {
    writeOutput({
      message: `Discovered ${entries.length} page(s), wrote 0 page(s) (dry-run)`,
    });
    for (const entry of entries) {
      writeOutput({
        message: formatEntryLine(entry, `${entry.url}.md`),
      });
    }
    return;
  }

  // Refresh — clear output dir
  if (options.refresh) {
    await fsPromises.rm(options.outputDir, { recursive: true, force: true });
  }

  await fsPromises.mkdir(options.outputDir, { recursive: true });

  // Fetch and save
  const { succeeded, failed } = await fetchWithConcurrency(
    entries,
    options.outputDir,
    options.workers
  );

  // Write index files for successfully fetched entries
  if (succeeded.length > 0) {
    await writeIndexFiles(succeeded, options.outputDir);
  }

  writeOutput({
    message: `Discovered ${entries.length} page(s), wrote ${succeeded.length} page(s)`,
  });
  for (const entry of succeeded) {
    writeOutput({
      message: formatEntryLine(
        entry,
        urlToFilePath(entry.url, options.outputDir)
      ),
    });
  }

  if (failed.length > 0) {
    for (const { entry, error } of failed) {
      writeError({
        message: `  - ${entry.title} [${entry.section.toLowerCase()}] FAILED: ${error}`,
      });
    }
    if (options.strict) {
      process.exit(ExitCode.FAILURE);
    }
  }
}

// ---------------------------------------------------------------------------
// Shared option helpers
// ---------------------------------------------------------------------------

/** Add all docs-specific options to a command. */
function addDocsOptions(command: Command): Command {
  return command
    .option(
      "--workflow <name>",
      `Filter by workflow category (repeatable) [possible values: ${VALID_WORKFLOWS.join(", ")}, all] [default: ${DEFAULT_WORKFLOWS.join(", ")}]`,
      (value: string, previous: string[]) => previous.concat([value]),
      [] as string[]
    )
    .option(
      "--output-dir <dir>",
      "Output directory for downloaded docs",
      DEFAULT_OUTPUT_DIR
    )
    .option("--dry-run", "Discover links only; do not write files", false)
    .option(
      "--refresh",
      "Refresh docs by clearing output directory before download",
      false
    )
    .option("--strict", "Fail command if any page download fails", false)
    .option(
      "--workers <n>",
      "Number of concurrent workers for docs downloads",
      parseInt,
      DEFAULT_WORKERS
    );
}

// ---------------------------------------------------------------------------
// Command factories
// ---------------------------------------------------------------------------

export function createDocsCommand(): Command {
  const command = new Command("docs");
  command.description("Manage workflow docs for coding agents");
  command.enablePositionalOptions();
  command.passThroughOptions();

  // All options live on the parent so `px docs --help` shows them
  addDocsOptions(command);
  command.action(docsFetchHandler);

  // `fetch` is a convenience alias — it re-parses its own argv so
  // `px docs fetch --workflow X` works identically to `px docs --workflow X`.
  const fetchCommand = new Command("fetch");
  fetchCommand.description(
    "Download workflow docs markdown from llms.txt index"
  );
  addDocsOptions(fetchCommand);
  fetchCommand.action(docsFetchHandler);
  command.addCommand(fetchCommand);

  return command;
}
