import * as childProcess from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { Command } from "commander";

import { ExitCode, getExitCodeForError } from "../exitCodes";
import { writeError, writeOutput } from "../io";
import {
  CLI_VERSION,
  compareSemanticVersions,
  fetchLatestPublishedCliVersion,
} from "../version";

const FILESYSTEM_PACKAGE_MANAGERS = ["npm", "pnpm", "bun"] as const;
const PACKAGE_MANAGER_PNPM_STORE_DIR = ".pnpm";
const CLI_PACKAGE_NAME = "@arizeai/phoenix-cli";
const CLI_COMMAND_NAMES = ["px", "phoenix-cli"] as const;
const DENO_INSTALL_MARKER = "# generated by deno install";
const CLI_PACKAGE_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  ".."
);

interface SelfUpdateOptions {
  check?: boolean;
}

type FilesystemPackageManager = (typeof FILESYSTEM_PACKAGE_MANAGERS)[number];
type SupportedPackageManager = FilesystemPackageManager | "deno";

/**
 * Parsed metadata from a Deno-generated CLI wrapper script.
 */
export interface DenoInstallScriptMetadata {
  /** Installed executable name, such as `px`. */
  executableName: string;
  /** Absolute path to the generated wrapper script. */
  executablePath: string;
  /** Deno install root containing the `bin/` directory. */
  rootPath: string;
  /** Original `deno run` flags preserved from the wrapper script. */
  runtimeArgs: string[];
}

/**
 * A concrete shell command that can be executed to update the CLI.
 */
export interface UpdateCommand {
  /** Executable name to invoke. */
  command: string;
  /** Ordered arguments passed to the executable. */
  args: string[];
  /** Human-readable command string shown to the user before execution. */
  displayCommand: string;
}

interface PackageManagerRoots {
  npmGlobalRoot?: string | null;
  pnpmGlobalRoot?: string | null;
  bunGlobalRoot?: string | null;
}

function getPackageManagerExecutable(
  packageManager: SupportedPackageManager
): string {
  return process.platform === "win32"
    ? `${packageManager}.cmd`
    : packageManager;
}

/**
 * Returns true when the candidate path is the same as or nested under
 * the provided root path.
 */
function isPathInside(rootPath: string, candidatePath: string): boolean {
  const relativePath = path.relative(rootPath, candidatePath);
  return (
    relativePath === "" ||
    (!relativePath.startsWith("..") && !path.isAbsolute(relativePath))
  );
}

function expandHomeDirectory(filePath: string): string {
  if (filePath === "~") {
    return os.homedir();
  }

  if (filePath.startsWith("~/")) {
    return path.join(os.homedir(), filePath.slice(2));
  }

  return filePath;
}

/**
 * Determine which supported package manager owns the current installation.
 *
 * @param params - package-manager lookup inputs
 * @param params.packageRoot - resolved package directory for the running CLI
 * @param params.npmGlobalRoot - `npm root -g` result when available
 * @param params.pnpmGlobalRoot - `pnpm root -g` result when available
 * @param params.bunGlobalRoot - Bun global `node_modules` root when available
 */
export function detectInstallPackageManager({
  packageRoot,
  npmGlobalRoot,
  pnpmGlobalRoot,
  bunGlobalRoot,
}: {
  packageRoot: string;
} & PackageManagerRoots): FilesystemPackageManager | null {
  if (bunGlobalRoot && isPathInside(bunGlobalRoot, packageRoot)) {
    return "bun";
  }

  if (pnpmGlobalRoot) {
    const pnpmStoreRoot = path.resolve(
      pnpmGlobalRoot,
      "..",
      PACKAGE_MANAGER_PNPM_STORE_DIR
    );
    if (
      isPathInside(pnpmGlobalRoot, packageRoot) ||
      isPathInside(pnpmStoreRoot, packageRoot)
    ) {
      return "pnpm";
    }
  }

  if (npmGlobalRoot && isPathInside(npmGlobalRoot, packageRoot)) {
    return "npm";
  }

  return null;
}

function getGlobalRoot(packageManager: "npm" | "pnpm"): string | null {
  try {
    return childProcess
      .execFileSync(
        getPackageManagerExecutable(packageManager),
        ["root", "-g"],
        {
          encoding: "utf8",
        }
      )
      .trim();
  } catch {
    return null;
  }
}

function getBunGlobalRoot(): string {
  const configuredGlobalDir =
    process.env.BUN_INSTALL_GLOBAL_DIR ??
    path.join(
      process.env.BUN_INSTALL ?? path.join(os.homedir(), ".bun"),
      "install",
      "global"
    );

  return path.join(expandHomeDirectory(configuredGlobalDir), "node_modules");
}

function getExecutableExtensions(): string[] {
  if (process.platform !== "win32") {
    return [""];
  }

  const pathExtensions = process.env.PATHEXT?.split(";").filter(Boolean);
  return pathExtensions && pathExtensions.length > 0
    ? pathExtensions
    : [".CMD", ".EXE", ".BAT", ""];
}

function isExecutable(filePath: string): boolean {
  try {
    fs.accessSync(
      filePath,
      process.platform === "win32" ? fs.constants.F_OK : fs.constants.X_OK
    );
    return true;
  } catch {
    return false;
  }
}

/**
 * Resolve an executable path using the current PATH, mirroring shell lookup.
 *
 * @param params - path lookup inputs
 * @param params.commandNames - executable names to search for on `PATH`
 */
export function findExecutableOnPath({
  commandNames,
}: {
  commandNames: readonly string[];
}): string | null {
  const pathValue = process.env.PATH;
  if (!pathValue) {
    return null;
  }

  const executableExtensions = getExecutableExtensions();
  for (const pathDirectory of pathValue.split(path.delimiter)) {
    if (!pathDirectory) {
      continue;
    }

    for (const commandName of commandNames) {
      for (const executableExtension of executableExtensions) {
        const candidatePath = path.join(
          pathDirectory,
          `${commandName}${executableExtension}`
        );
        if (isExecutable(candidatePath)) {
          return candidatePath;
        }
      }
    }
  }

  return null;
}

/**
 * Tokenize a simple shell command line so Deno install wrappers can be parsed.
 *
 * @param command - shell command line to tokenize
 */
export function tokenizeShellCommand(command: string): string[] | null {
  const tokens: string[] = [];
  let currentToken = "";
  let quote: '"' | "'" | null = null;
  let isEscaped = false;

  for (const character of command) {
    if (isEscaped) {
      currentToken += character;
      isEscaped = false;
      continue;
    }

    if (quote === "'") {
      if (character === "'") {
        quote = null;
      } else {
        currentToken += character;
      }
      continue;
    }

    if (quote === '"') {
      if (character === '"') {
        quote = null;
      } else if (character === "\\") {
        isEscaped = true;
      } else {
        currentToken += character;
      }
      continue;
    }

    if (character === "'" || character === '"') {
      quote = character;
      continue;
    }

    if (character === "\\") {
      isEscaped = true;
      continue;
    }

    if (/\s/.test(character)) {
      if (currentToken.length > 0) {
        tokens.push(currentToken);
        currentToken = "";
      }
      continue;
    }

    currentToken += character;
  }

  if (quote || isEscaped) {
    return null;
  }

  if (currentToken.length > 0) {
    tokens.push(currentToken);
  }

  return tokens;
}

/**
 * Parse a Deno `deno install -g` wrapper for the Phoenix CLI so the command
 * can replay the original install with a newer npm package version.
 *
 * @param params - Deno wrapper inputs
 * @param params.executablePath - absolute path to the generated executable
 * @param params.scriptContent - wrapper script contents to inspect
 */
export function parseDenoInstallScript({
  executablePath,
  scriptContent,
}: {
  executablePath: string;
  scriptContent: string;
}): DenoInstallScriptMetadata | null {
  if (!scriptContent.includes(DENO_INSTALL_MARKER)) {
    return null;
  }

  const execLine = scriptContent
    .split("\n")
    .map((line) => line.trim())
    .find((line) => line.startsWith("exec "));
  if (!execLine) {
    return null;
  }

  const tokens = tokenizeShellCommand(execLine.slice("exec ".length));
  if (!tokens || tokens.length < 3) {
    return null;
  }

  const executableToken = path.basename(tokens[0]);
  if (executableToken !== "deno" || tokens[1] !== "run") {
    return null;
  }

  const specifierIndex = tokens.findIndex((token) =>
    token.startsWith(`npm:${CLI_PACKAGE_NAME}`)
  );
  if (specifierIndex === -1) {
    return null;
  }

  const runtimeArgs: string[] = [];
  for (let index = 2; index < specifierIndex; index++) {
    const token = tokens[index];
    if (token === "--lock") {
      index += 1;
      continue;
    }
    if (token.startsWith("--lock=")) {
      continue;
    }
    runtimeArgs.push(token);
  }

  const executableDirectory = path.dirname(executablePath);
  const rootPath =
    path.basename(executableDirectory) === "bin"
      ? path.dirname(executableDirectory)
      : executableDirectory;

  return {
    executableName: path.basename(executablePath),
    executablePath,
    rootPath,
    runtimeArgs,
  };
}

function getCurrentDenoInstallScript(): DenoInstallScriptMetadata | null {
  const executablePath = findExecutableOnPath({
    commandNames: CLI_COMMAND_NAMES,
  });
  if (!executablePath) {
    return null;
  }

  try {
    const scriptContent = fs.readFileSync(executablePath, "utf8");
    return parseDenoInstallScript({
      executablePath,
      scriptContent,
    });
  } catch {
    return null;
  }
}

/**
 * Build the exact package-manager command that will install the requested
 * version globally.
 *
 * @param params - command construction inputs
 * @param params.packageManager - owning package manager for the current install
 * @param params.packageName - npm package name to install
 * @param params.version - exact version to install
 */
export function buildUpdateCommand({
  packageManager,
  packageName,
  version,
}: {
  packageManager: "npm" | "pnpm" | "bun";
  packageName: string;
  version: string;
}): UpdateCommand {
  const packageSpecifier = `${packageName}@${version}`;
  const command = getPackageManagerExecutable(packageManager);
  const args =
    packageManager === "npm"
      ? ["install", "--global", packageSpecifier]
      : ["add", "--global", packageSpecifier];

  return {
    command,
    args,
    displayCommand: [packageManager, ...args].join(" "),
  };
}

/**
 * Build the exact Deno reinstall command for a wrapper generated by
 * `deno install --global`.
 *
 * @param params - Deno reinstall inputs
 * @param params.installScript - parsed metadata from the existing Deno wrapper
 * @param params.packageName - npm package name to reinstall
 * @param params.version - exact version to install
 */
export function buildDenoUpdateCommand({
  installScript,
  packageName,
  version,
}: {
  installScript: DenoInstallScriptMetadata;
  packageName: string;
  version: string;
}): UpdateCommand {
  const command = getPackageManagerExecutable("deno");
  const args = [
    "install",
    "--global",
    "--force",
    "--root",
    installScript.rootPath,
    "--name",
    installScript.executableName,
    ...installScript.runtimeArgs,
    `npm:${packageName}@${version}`,
  ];

  return {
    command,
    args,
    displayCommand: ["deno", ...args].join(" "),
  };
}

function runUpdateCommand(updateCommand: UpdateCommand): number {
  const result = childProcess.spawnSync(
    updateCommand.command,
    updateCommand.args,
    {
      stdio: "inherit",
    }
  );

  if (result.error) {
    throw result.error;
  }

  return result.status ?? ExitCode.FAILURE;
}

function getCurrentInstallPackageManager({
  packageRoot,
}: {
  packageRoot: string;
}): FilesystemPackageManager | null {
  return detectInstallPackageManager({
    packageRoot,
    npmGlobalRoot: getGlobalRoot("npm"),
    pnpmGlobalRoot: getGlobalRoot("pnpm"),
    bunGlobalRoot: getBunGlobalRoot(),
  });
}

function formatVersionStatus({
  currentVersion,
  latestVersion,
}: {
  currentVersion: string;
  latestVersion: string;
}): string {
  return [
    `Current version: ${currentVersion}`,
    `Latest version: ${latestVersion}`,
  ].join("\n");
}

async function selfUpdateHandler(options: SelfUpdateOptions): Promise<void> {
  try {
    const latestVersion = await fetchLatestPublishedCliVersion();
    if (!latestVersion) {
      throw new TypeError("Unable to fetch latest CLI version from npm");
    }
    const versionComparison = compareSemanticVersions({
      leftVersion: latestVersion,
      rightVersion: CLI_VERSION,
    });
    if (versionComparison === null) {
      throw new Error(`Invalid published CLI version: ${latestVersion}`);
    }

    writeOutput({
      message: formatVersionStatus({
        currentVersion: CLI_VERSION,
        latestVersion,
      }),
    });

    if (versionComparison <= 0) {
      writeOutput({ message: "px is up to date." });
      return;
    }

    if (options.check) {
      writeOutput({
        message: "Update available. Run `px self update` to install it.",
      });
      return;
    }

    const packageManager = getCurrentInstallPackageManager({
      packageRoot: CLI_PACKAGE_ROOT,
    });
    const denoInstallScript =
      packageManager == null ? getCurrentDenoInstallScript() : null;

    const updateCommand =
      packageManager != null
        ? buildUpdateCommand({
            packageManager,
            packageName: CLI_PACKAGE_NAME,
            version: latestVersion,
          })
        : denoInstallScript
          ? buildDenoUpdateCommand({
              installScript: denoInstallScript,
              packageName: CLI_PACKAGE_NAME,
              version: latestVersion,
            })
          : null;

    if (!updateCommand) {
      writeError({
        message:
          "Error: Automatic updates are only supported for global npm, pnpm, bun, or Deno installs of @arizeai/phoenix-cli.",
      });
      process.exit(ExitCode.FAILURE);
    }

    writeOutput({
      message: `Updating via ${updateCommand.displayCommand}`,
    });

    const exitCode = runUpdateCommand(updateCommand);
    if (exitCode !== ExitCode.SUCCESS) {
      process.exit(exitCode);
    }

    writeOutput({
      message: `Updated px to ${latestVersion}.`,
    });
  } catch (error) {
    writeError({
      message: `Error: ${error instanceof Error ? error.message : String(error)}`,
    });
    process.exit(getExitCodeForError(error));
  }
}

function createSelfUpdateCommand(): Command {
  const command = new Command("update");

  command
    .description("Update the installed Phoenix CLI to the latest npm version")
    .option("--check", "Only check whether a newer version is available")
    .action(selfUpdateHandler);

  return command;
}

export function createSelfCommand(): Command {
  const command = new Command("self");

  command.description("Manage the installed Phoenix CLI");
  command.addCommand(createSelfUpdateCommand());

  return command;
}
