"""Vercel AI data-stream-protocol message types."""

from pydantic import TypeAdapter

from .phoenix_types import (
    AssistantMessageMetadata,
    AssistantMessageMetadataTraceIds,
    AssistantMessageMetadataUsage,
    AssistantMessageMetadataUsageTokenDetails,
    AssistantMessageMetadataUsageTokens,
    CompactionMessageMetadata,
    MessageMetadata,
    PhoenixUIMessage,
    TurnTraceContext,
    UserMessageMetadata,
)
from .provider_metadata import (
    ToolCallCallbackProviderMetadata,
    ToolCallProviderMetadata,
    ToolExecutionEnvironment,
)
from .request_types import (
    BaseUIPart,
    DataUIPart,
    DynamicToolApprovalRequestedPart,
    DynamicToolApprovalRespondedPart,
    DynamicToolInputAvailablePart,
    DynamicToolInputStreamingPart,
    DynamicToolOutputAvailablePart,
    DynamicToolOutputDeniedPart,
    DynamicToolOutputErrorPart,
    DynamicToolUIPart,
    FileUIPart,
    JSONValue,
    ProviderMetadata,
    ReasoningUIPart,
    RegenerateMessage,
    RequestData,
    SourceDocumentUIPart,
    SourceUrlUIPart,
    StepStartUIPart,
    SubmitMessage,
    TextUIPart,
    ToolApproval,
    ToolApprovalRequested,
    ToolApprovalRequestedPart,
    ToolApprovalResponded,
    ToolApprovalRespondedPart,
    ToolInputAvailablePart,
    ToolInputStreamingPart,
    ToolOutputAvailablePart,
    ToolOutputDeniedPart,
    ToolOutputErrorPart,
    ToolUIPart,
    UIMessage,
    UIMessagePart,
)

PhoenixUIMessageAdapter = TypeAdapter(PhoenixUIMessage)

__all__ = [
    "AssistantMessageMetadata",
    "AssistantMessageMetadataTraceIds",
    "AssistantMessageMetadataUsage",
    "AssistantMessageMetadataUsageTokenDetails",
    "AssistantMessageMetadataUsageTokens",
    "BaseUIPart",
    "CompactionMessageMetadata",
    "DataUIPart",
    "DynamicToolApprovalRequestedPart",
    "DynamicToolApprovalRespondedPart",
    "DynamicToolInputAvailablePart",
    "DynamicToolInputStreamingPart",
    "DynamicToolOutputAvailablePart",
    "DynamicToolOutputDeniedPart",
    "DynamicToolOutputErrorPart",
    "DynamicToolUIPart",
    "FileUIPart",
    "JSONValue",
    "MessageMetadata",
    "PhoenixUIMessage",
    "PhoenixUIMessageAdapter",
    "ProviderMetadata",
    "ReasoningUIPart",
    "RegenerateMessage",
    "RequestData",
    "SourceDocumentUIPart",
    "SourceUrlUIPart",
    "StepStartUIPart",
    "SubmitMessage",
    "TextUIPart",
    "ToolApproval",
    "ToolApprovalRequested",
    "ToolApprovalRequestedPart",
    "ToolApprovalResponded",
    "ToolApprovalRespondedPart",
    "ToolCallCallbackProviderMetadata",
    "ToolCallProviderMetadata",
    "ToolExecutionEnvironment",
    "ToolInputAvailablePart",
    "ToolInputStreamingPart",
    "ToolOutputAvailablePart",
    "ToolOutputDeniedPart",
    "ToolOutputErrorPart",
    "ToolUIPart",
    "TurnTraceContext",
    "UIMessage",
    "UIMessagePart",
    "UserMessageMetadata",
]
