{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ template "phoenix.ingress" . }}"
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.ingress.labels }}
  labels:
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
{{- if .Values.ingress.annotations}}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - secretName: {{ template "phoenix.tlsCoreSecretForIngress" . }}
    {{- if .Values.ingress.host }}
    hosts:
    - {{ .Values.ingress.host }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.api_path }}
        pathType: {{ .Values.ingress.path_type }}
        backend:
          service:
            name: {{ template "phoenix.service" . }}
            port:
              number: {{ template "phoenix.appPort" . }}
    {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
    {{- end }}
{{- end }}
