apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.name }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
{{- if .Values.auth.secret }}
{{- range $authSecrets := .Values.auth.secret }}
  {{ $authSecrets.key }}: {{ $authSecrets.value | default (randAlphaNum 32) | b64enc }}
{{- end }}
{{- end }}