apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.name }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
{{- if .Values.auth.secret }}
{{- range $authSecrets := .Values.auth.secret }}
  {{- if eq $authSecrets.key "PHOENIX_DEFAULT_ADMIN_INITIAL_PASSWORD" }}
  {{ $authSecrets.key }}: {{ ($authSecrets.value | default $.Values.auth.defaultAdminPassword) | b64enc }}
  {{- else }}
  {{ $authSecrets.key }}: {{ $authSecrets.value | default (randAlphaNum 32) | b64enc }}
  {{- end }}
{{- end }}
{{- end }}