apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
{{- if .Values.auth.secret }}
{{- range $authSecrets := .Values.auth.secret }}
  {{- if and (eq $authSecrets.key "PHOENIX_DEFAULT_ADMIN_INITIAL_PASSWORD") (not $authSecrets.valueFrom) }}
  {{ $authSecrets.key }}: {{ (empty $authSecrets.value | ternary $.Values.auth.defaultAdminPassword $authSecrets.value) | b64enc }}
  {{- else if not $authSecrets.valueFrom }}
  {{ $authSecrets.key }}: {{ $authSecrets.value | default (randAlphaNum 32) | b64enc }}
  {{- end }}
{{- end }}
{{- end }}

{{- if and .Values.auth.oauth2.enabled .Values.auth.oauth2.providers }}
{{- range $provider_name, $provider_config := .Values.auth.oauth2.providers }}
{{- if $provider_config.client_secret }}
{{- $provider_upper := $provider_name | upper }}
  PHOENIX_OAUTH2_{{ $provider_upper }}_CLIENT_SECRET: {{ $provider_config.client_secret | b64enc }}
{{- end }}
{{- end }}
{{- end }}
