apiVersion: v1
kind: Service
metadata:
  name: {{ template "phoenix.service" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: {{ template "phoenix.grpcPortName" . }}
      port: {{ template "phoenix.grpcPort" . }}
    - name: {{ template "phoenix.appPortName" . }}
      port: {{ template "phoenix.appPort" . }}
    - name: {{ template "phoenix.metricsPortName" . }}
      port: {{ template "phoenix.metricsPort" . }} 
  selector:
    component: {{ .Release.Name }}
