name: 💡 Feature Request
description: Suggest an idea for this project
title: "[ENHANCEMENT]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A description of what you want to happen.
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe any alternative solutions you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
      
  - type: input
    id: social-handle
    attributes:
      label: Social Media Handle
      description: If you'd like to be recognized for suggesting a new feature that makes it into Phoenix
      placeholder: "Optional"
    validations:
      required: false