# /// script
# dependencies = [
#   "arize-phoenix",
# ]
# ///
# ruff: noqa: E501
"""SQLite DDL Extractor.

Extracts DDL from a SQLite database and outputs it to a file, grouped by table
and sorted deterministically. The generated schema is automatically validated by
replaying it into a fresh in-memory database and re-rendering it.

Supports both ephemeral and external SQLite databases:
- Ephemeral mode: Creates a temporary SQLite database with migrations (default)
- External mode: Reads an existing SQLite database file (no migrations)

DDL is reformatted from the CREATE text sqlite_master stores, not rebuilt from
catalog queries. SQLite exposes no catalog for CHECK constraints, and
PRAGMA index_list() flags a partial index without exposing its WHERE clause, so
reconstruction would silently drop both.

Usage:
    # Create ephemeral SQLite database, run migrations, extract DDL (default behavior)
    python generate_ddl_sqlite.py

    # Read an existing SQLite database (no migrations run)
    python generate_ddl_sqlite.py --external --database /path/to/phoenix.db

    # Specify custom output file with ephemeral mode (default)
    python generate_ddl_sqlite.py --output /path/to/schema.sql

Requirements:
    pip install arize-phoenix
"""

from __future__ import annotations

import argparse
import re
import sqlite3
import sys
import warnings
from contextlib import contextmanager
from dataclasses import dataclass, field
from io import StringIO
from pathlib import Path
from tempfile import NamedTemporaryFile, TemporaryDirectory
from typing import Any, Iterator

from alembic import command
from alembic.config import Config
from sqlalchemy import URL, create_engine
from sqlalchemy.exc import SAWarning

import phoenix.db

TABLE_INDENT = "    "
CONTINUATION_INDENT = "    "  # added to TABLE_INDENT on wrapped lines
MAX_LINE_LENGTH = 88
STATEMENT_PREVIEW_LENGTH = 200  # caps statement text quoted in error messages
EPHEMERAL_DATABASE_NAME = "phoenix.db"
CANONICAL_OUTPUT = Path(__file__).resolve().parents[2] / "src/phoenix/db/ddl/sqlite_schema.sql"
EXTERNAL_OUTPUT = Path(__file__).with_name("sqlite_schema.sql")
SCHEMA_PREAMBLE = "-- Generated by `make schema-ddl`; do not edit manually.\n\n"
EXPRESSION_INDEX_REFLECTION_WARNING = r"Skipped unsupported reflection of expression-based index .*"

# Clause keywords a long definition is broken before, giving one clause per
# line. Wrapping is driven only by the normalized text, so a definition re-read
# from a replayed database wraps identically and rendering stays idempotent.
# CONSTRAINT and the constraint-type keywords are ignored at position 0, where
# they open the definition rather than a following clause.
CLAUSE_KEYWORDS = (
    "CONSTRAINT",
    "PRIMARY KEY",
    "FOREIGN KEY",
    "UNIQUE",
    "CHECK",
    "REFERENCES",
    "ON DELETE",
    "ON UPDATE",
    "DEFERRABLE",
    "NOT DEFERRABLE",
)

# SQLite's bookkeeping objects (sqlite_sequence, sqlite_stat1, ...) are recreated
# on demand and are not part of the application schema. ESCAPE is required
# because '_' is a LIKE wildcard, which would also match e.g. "sqlitexschema".
SCHEMA_OBJECTS_QUERY = r"""
    SELECT type, name, tbl_name, sql
    FROM sqlite_master
    WHERE sql IS NOT NULL          -- implicit indexes (sqlite_autoindex_*) have no DDL text
      AND name NOT LIKE 'sqlite\_%' ESCAPE '\'
      AND tbl_name NOT LIKE 'sqlite\_%' ESCAPE '\'
    ORDER BY name
"""

# Matches the CREATE statement of a virtual table, whose backing shadow tables
# appear in sqlite_master as ordinary tables.
VIRTUAL_TABLE_PATTERN = re.compile(r"CREATE\s+VIRTUAL\s+TABLE\b", re.IGNORECASE)

# A bare identifier in the output must re-parse as the same identifier: ASCII
# word characters only, not starting with a digit, and not a keyword.
PLAIN_IDENTIFIER_PATTERN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")

# SQLAlchemy emits FOREIGN KEY(cols) with no space while writing every other
# constraint keyword with one. Normalizing keeps the rendered file internally
# consistent, and matching the PostgreSQL schema makes the two diffable.
CLAUSE_SPACING_PATTERN = re.compile(r"\b(FOREIGN KEY|PRIMARY KEY|UNIQUE|CHECK|REFERENCES)\(")

# Opening -> closing delimiter for string literals and quoted identifiers.
# Scanners skip these regions wholesale: a ',', '(' or '--' inside one is data,
# not syntax.
LITERAL_DELIMITERS = {"'": "'", '"': '"', "`": "`", "[": "]"}

# Emission order for table-level constraints, keyed by their opening keyword.
# Constraints are order-independent in SQLite, and a table rebuilt during a
# migration re-emits them in a run-dependent order; sorting keeps a regenerated
# file from churning without a schema change.
CONSTRAINT_TYPE_ORDER = {"PRIMARY": 0, "UNIQUE": 1, "CHECK": 2, "FOREIGN": 3}


@dataclass
class TableInfo:
    """Complete table DDL information, as stored by SQLite."""

    table_name: str
    create_sql: str
    indexes: list[str] = field(default_factory=list)
    triggers: list[str] = field(default_factory=list)
    referenced_tables: set[str] = field(default_factory=set)


@dataclass
class SchemaInfo:
    """Every schema object extracted from one database."""

    tables: list[TableInfo] = field(default_factory=list)
    views: list[str] = field(default_factory=list)


def _skip_literal(sql: str, start: int) -> int:
    """Return the index just past the literal or quoted identifier at `start`."""
    closing_delimiter = LITERAL_DELIMITERS[sql[start]]
    index = start + 1
    while index < len(sql):
        if sql[index] != closing_delimiter:
            index += 1
            continue
        # SQLite escapes a delimiter inside '', "", and `` by doubling it.
        # Bracket quoting has no escape mechanism at all.
        if (
            closing_delimiter != "]"
            and index + 1 < len(sql)
            and sql[index + 1] == closing_delimiter
        ):
            index += 2
            continue
        return index + 1
    raise ValueError(f"Unterminated {sql[start]!r} literal in: {_preview(sql[start:])}")


def normalize_sql(sql: str) -> str:
    """Collapse a statement onto one line, dropping comments and runs of whitespace.

    Every rendering decision is made from this canonical form and never from the
    original layout, which is what makes rendering idempotent: a statement
    re-read from a replayed database normalizes to the string it was rendered
    from.

    Comments are dropped rather than preserved because joining lines around a
    surviving '--' would comment out the rest of the statement.
    """
    normalized: list[str] = []
    index, length = 0, len(sql)
    space_pending = False

    while index < length:
        character = sql[index]

        if sql.startswith("--", index):
            newline = sql.find("\n", index)
            index = length if newline == -1 else newline
            space_pending = True
            continue

        if sql.startswith("/*", index):
            comment_end = sql.find("*/", index + 2)
            if comment_end == -1:
                raise ValueError(f"Unterminated block comment in: {_preview(sql[index:])}")
            index = comment_end + 2
            space_pending = True
            continue

        if character.isspace():
            space_pending = True
            index += 1
            continue

        if space_pending and normalized:
            normalized.append(" ")
        space_pending = False

        if character in LITERAL_DELIMITERS:
            literal_end = _skip_literal(sql, index)
            normalized.append(sql[index:literal_end])
            index = literal_end
            continue

        normalized.append(character)
        index += 1

    return "".join(normalized)


def _split_top_level(text: str) -> list[str]:
    """Split on commas that sit outside every parenthesis and literal.

    Definitions are comma-separated at the top level, but so are CHECK
    expression arguments and REFERENCES column lists, which are nested.
    """
    parts: list[str] = []
    start, depth = 0, 0
    index, length = 0, len(text)

    while index < length:
        character = text[index]
        if character in LITERAL_DELIMITERS:
            index = _skip_literal(text, index)
            continue
        if character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
        elif character == "," and depth == 0:
            parts.append(text[start:index].strip())
            start = index + 1
        index += 1

    parts.append(text[start:].strip())
    return [part for part in parts if part]


def _find_matching_parenthesis(text: str, opening_index: int) -> int:
    """Return the index of the ')' that closes the '(' at `opening_index`."""
    depth = 0
    index, length = opening_index, len(text)

    while index < length:
        character = text[index]
        if character in LITERAL_DELIMITERS:
            index = _skip_literal(text, index)
            continue
        if character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
            if depth == 0:
                return index
        index += 1

    raise ValueError(f"Unbalanced parentheses in: {_preview(text)}")


def _is_identifier_character(character: str) -> bool:
    """Report whether a character can appear inside a bare SQL identifier."""
    return character.isalnum() or character in "_$"


def _find_top_level_keyword(text: str, keyword: str) -> int | None:
    """Locate a keyword outside every parenthesis and literal, or return None.

    Finds a partial index's WHERE without matching one nested in a subquery, or
    the same letters inside an identifier or string literal.
    """
    lowered_text, lowered_keyword = text.lower(), keyword.lower()
    depth = 0
    index, length = 0, len(text)

    while index < length:
        character = text[index]
        if character in LITERAL_DELIMITERS:
            index = _skip_literal(text, index)
            continue
        if character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
        elif depth == 0 and lowered_text.startswith(lowered_keyword, index):
            end = index + len(keyword)
            before_is_boundary = index == 0 or not _is_identifier_character(text[index - 1])
            after_is_boundary = end >= length or not _is_identifier_character(text[end])
            if before_is_boundary and after_is_boundary:
                return index
        index += 1

    return None


def _last_identifier_span(text: str) -> tuple[int, int]:
    """Return the span of the final identifier token in `text`.

    The object name is the last identifier in a CREATE header regardless of
    form (quoted, IF NOT EXISTS, schema-qualified), so keeping the most recent
    token avoids parsing the prefix.
    """
    span: tuple[int, int] | None = None
    index, length = 0, len(text)

    while index < length:
        character = text[index]
        if character in LITERAL_DELIMITERS:
            literal_end = _skip_literal(text, index)
            span = (index, literal_end)
            index = literal_end
            continue
        if _is_identifier_character(character):
            end = index
            while end < length and _is_identifier_character(text[end]):
                end += 1
            span = (index, end)
            index = end
            continue
        index += 1

    if span is None:
        raise ValueError(f"No identifier found in: {_preview(text)}")
    return span


def _iter_tokens(text: str) -> Iterator[tuple[str, bool]]:
    """Yield each identifier or literal in `text` as (token, is_quoted)."""
    index, length = 0, len(text)

    while index < length:
        character = text[index]
        if character in LITERAL_DELIMITERS:
            literal_end = _skip_literal(text, index)
            yield text[index:literal_end], True
            index = literal_end
            continue
        if _is_identifier_character(character):
            end = index
            while end < length and _is_identifier_character(text[end]):
                end += 1
            yield text[index:end], False
            index = end
            continue
        index += 1


def _constraint_sort_key(definition: str) -> tuple[int, str] | None:
    """Rank a table-level constraint, or return None for a column definition.

    SQLite distinguishes the two by the opening keyword: a bare CONSTRAINT,
    PRIMARY, UNIQUE, CHECK, or FOREIGN opens a table constraint, while anything
    else -- including those same words quoted -- is a column name. A
    column-level CHECK follows its column name rather than opening the
    definition, so it cannot be mistaken for a table constraint.
    """
    tokens = [token for _, token in zip(range(3), _iter_tokens(definition))]
    if not tokens:
        raise ValueError(f"Empty table definition in: {_preview(definition)}")

    first_token, first_is_quoted = tokens[0]
    if first_is_quoted:
        return None

    if first_token.upper() != "CONSTRAINT":
        order = CONSTRAINT_TYPE_ORDER.get(first_token.upper())
        return None if order is None else (order, "")

    if len(tokens) < 3:
        raise ValueError(f"Named constraint has no type: {_preview(definition)}")
    name_token, _ = tokens[1]
    type_token, type_is_quoted = tokens[2]
    order = None if type_is_quoted else CONSTRAINT_TYPE_ORDER.get(type_token.upper())
    if order is None:
        raise ValueError(f"Unrecognized constraint type in: {_preview(definition)}")

    return (order, _decode_identifier(name_token))


def _order_definitions(definitions: list[str]) -> list[str]:
    """Keep columns in declaration order and sort table constraints after them.

    Column order is part of the schema, since it determines what SELECT *
    returns; constraint order carries no meaning. Pairing each constraint with
    its sort key makes the definition text the final tiebreak, so constraints
    sharing a key still land in a fixed order.
    """
    columns: list[str] = []
    constraints: list[tuple[tuple[int, str], str]] = []

    for definition in definitions:
        sort_key = _constraint_sort_key(definition)
        if sort_key is None:
            columns.append(definition)
        else:
            constraints.append((sort_key, definition))

    return columns + [definition for _, definition in sorted(constraints)]


def _normalize_clause_spacing(definition: str) -> str:
    """Put a space between a constraint keyword and its parenthesized list.

    Literal-aware, so the same characters inside a string default or a quoted
    identifier are left alone.
    """
    normalized: list[str] = []
    index, length = 0, len(definition)

    while index < length:
        if definition[index] in LITERAL_DELIMITERS:
            literal_end = _skip_literal(definition, index)
            normalized.append(definition[index:literal_end])
            index = literal_end
            continue
        matched = CLAUSE_SPACING_PATTERN.match(definition, index)
        if matched is not None:
            normalized.append(f"{matched.group(1)} (")
            index = matched.end()
            continue
        normalized.append(definition[index])
        index += 1

    return "".join(normalized)


def _find_clause_breaks(definition: str) -> list[int]:
    """Return the offsets of clause keywords that may start a wrapped line."""
    breaks: set[int] = set()
    for keyword in CLAUSE_KEYWORDS:
        search_from = 0
        while True:
            offset = _find_top_level_keyword(definition[search_from:], keyword)
            if offset is None:
                break
            absolute = search_from + offset
            if absolute > 0:
                breaks.add(absolute)
            search_from = absolute + len(keyword)
    return sorted(breaks)


def _split_boolean_operands(expression: str) -> list[tuple[str, str]]:
    """Split at top-level AND/OR into (leading operator, operand) pairs."""
    breaks: list[tuple[int, str]] = []
    for keyword in ("AND", "OR"):
        search_from = 0
        while True:
            offset = _find_top_level_keyword(expression[search_from:], keyword)
            if offset is None:
                break
            breaks.append((search_from + offset, keyword))
            search_from += offset + len(keyword)
    breaks.sort()

    if not breaks:
        return [("", expression)]

    operands = [("", expression[: breaks[0][0]].strip())]
    for position, (offset, keyword) in enumerate(breaks):
        end = breaks[position + 1][0] if position + 1 < len(breaks) else len(expression)
        operands.append((keyword, expression[offset + len(keyword) : end].strip()))
    return operands


def _is_parenthesized(text: str) -> bool:
    """Report whether the whole of `text` sits inside one pair of parentheses."""
    return (
        text.startswith("(")
        and text.endswith(")")
        and _find_matching_parenthesis(text, 0) == len(text) - 1
    )


def _wrap_boolean_expression(expression: str, indent: str) -> list[str]:
    """Lay out a boolean expression one operand per line, recursing into groups.

    Operators lead their line so the structure of a long predicate is visible
    down the left margin rather than buried mid-line.
    """
    if len(indent) + len(expression) <= MAX_LINE_LENGTH:
        return [f"{indent}{expression}"]

    operands = _split_boolean_operands(expression)
    if len(operands) < 2:
        if _is_parenthesized(expression):
            inner = _wrap_boolean_expression(expression[1:-1].strip(), indent + CONTINUATION_INDENT)
            return [f"{indent}(", *inner, f"{indent})"]
        return [f"{indent}{expression}"]

    lines: list[str] = []
    for operator, operand in operands:
        prefix = f"{operator} " if operator else ""
        candidate = f"{indent}{prefix}{operand}"
        if len(candidate) <= MAX_LINE_LENGTH or not _is_parenthesized(operand):
            lines.append(candidate)
            continue
        inner = _wrap_boolean_expression(operand[1:-1].strip(), indent + CONTINUATION_INDENT)
        lines.append(f"{indent}{prefix}(")
        lines.extend(inner)
        lines.append(f"{indent})")
    return lines


def _expand_check_expression(segment: str, indent: str) -> list[str] | None:
    """Break a CHECK across lines by laying out its predicate, or return None."""
    if not segment.upper().startswith("CHECK "):
        return None
    opening = segment.find("(")
    if opening == -1 or _find_matching_parenthesis(segment, opening) != len(segment) - 1:
        return None

    predicate = segment[opening + 1 : -1].strip()
    body = _wrap_boolean_expression(predicate, indent + CONTINUATION_INDENT)
    if len(body) < 2:
        return None
    return [f"{indent}CHECK (", *body, f"{indent})"]


def _expand_value_list(line: str, indent: str) -> list[str] | None:
    """Put each element of an IN list on its own line, or return None.

    Mirrors the array formatting in the PostgreSQL schema: a diff then shows
    which enum values changed rather than one rewritten line.
    """
    # The list sits inside the CHECK parentheses, so this scans at any depth and
    # only skips literals, where "IN" would be data.
    keyword = None
    index, length = 0, len(line)
    while index < length:
        if line[index] in LITERAL_DELIMITERS:
            index = _skip_literal(line, index)
            continue
        if line.upper().startswith("IN", index):
            before = index == 0 or not _is_identifier_character(line[index - 1])
            after = index + 2 >= length or not _is_identifier_character(line[index + 2])
            if before and after:
                keyword = index
                break
        index += 1
    if keyword is None:
        return None

    opening = line.find("(", keyword)
    if opening == -1:
        return None
    closing = _find_matching_parenthesis(line, opening)
    values = _split_top_level(line[opening + 1 : closing])
    if len(values) < 2:
        return None

    element_indent = indent + CONTINUATION_INDENT
    return [
        f"{line[: opening + 1].rstrip()}",
        *[f"{element_indent}{value}," for value in values[:-1]],
        f"{element_indent}{values[-1]}",
        f"{indent}{line[closing:]}",
    ]


def wrap_definition(definition: str, indent: str) -> list[str]:
    """Break a long column or constraint definition into indented lines.

    A definition that fits is left alone. One that does not is split before
    every clause keyword it contains, and any resulting line still over the
    limit has its IN list expanded.
    """
    if len(indent) + len(definition) <= MAX_LINE_LENGTH:
        return [f"{indent}{definition}"]

    breaks = _find_clause_breaks(definition)
    bounds = [0, *breaks, len(definition)]
    segments = [definition[start:end].strip() for start, end in zip(bounds, bounds[1:])]
    segments = [segment for segment in segments if segment]

    continuation = indent + CONTINUATION_INDENT
    lines: list[str] = []
    for position, segment in enumerate(segments):
        line_indent = indent if position == 0 else continuation
        line = f"{line_indent}{segment}"
        if len(line) <= MAX_LINE_LENGTH:
            lines.append(line)
            continue
        expanded = _expand_check_expression(segment, line_indent) or _expand_value_list(
            segment, line_indent
        )
        lines.extend(expanded if expanded else [line])
    return lines


def _decode_identifier(token: str) -> str:
    """Strip quoting from an identifier token, undoing any delimiter doubling."""
    if token and token[0] in LITERAL_DELIMITERS:
        closing_delimiter = LITERAL_DELIMITERS[token[0]]
        inner = token[1:-1]
        if closing_delimiter == "]":
            return inner
        return inner.replace(closing_delimiter * 2, closing_delimiter)
    return token


def quote_identifier_if_needed(identifier: str) -> str:
    """Quote a SQLite identifier only when bare use would change its meaning.

    Alembic's batch migrations rewrite a table with its name quoted while plain
    CREATE TABLE emits it bare, so a table's rendered name would otherwise
    depend on which migration last touched it.
    """
    if PLAIN_IDENTIFIER_PATTERN.fullmatch(identifier) and identifier.lower() not in SQLITE_KEYWORDS:
        return identifier
    escaped = identifier.replace('"', '""')
    return f'"{escaped}"'


def _preview(text: str) -> str:
    """Truncate a statement for inclusion in an error message."""
    if len(text) <= STATEMENT_PREVIEW_LENGTH:
        return text
    return text[:STATEMENT_PREVIEW_LENGTH] + "..."


def _terminate(statement: str) -> str:
    """Append a statement terminator, which sqlite_master.sql never stores."""
    return statement if statement.endswith(";") else f"{statement};"


def render_create_table(create_sql: str) -> str:
    """Reformat a CREATE TABLE with one column or constraint per line.

    SQLite stores the statement as issued, so a column appended by a later
    ALTER TABLE shares a line with the column before it. Re-splitting on
    top-level commas keeps a schema diff limited to what actually changed.
    """
    normalized = normalize_sql(create_sql)
    header, body, trailer = _split_create_table(normalized)

    name_start, name_end = _last_identifier_span(header)
    table_name = _decode_identifier(header[name_start:name_end])
    header = header[:name_start] + quote_identifier_if_needed(table_name)

    definitions = [
        _normalize_clause_spacing(definition)
        for definition in _order_definitions(_split_top_level(body))
    ]
    if not definitions:
        raise ValueError(f"CREATE TABLE has no column definitions: {_preview(normalized)}")

    rendered = ["\n".join(wrap_definition(definition, TABLE_INDENT)) for definition in definitions]
    lines = [f"{header} ("]
    lines.append(",\n".join(rendered))
    lines.append(f"){' ' + trailer if trailer else ''};")
    return "\n".join(lines)


def _split_create_table(normalized_sql: str) -> tuple[str, str, str]:
    """Split a normalized CREATE TABLE into header, definition body, and trailer.

    The trailer carries table options such as WITHOUT ROWID and STRICT, which
    follow the closing parenthesis and must be preserved verbatim.
    """
    index, length = 0, len(normalized_sql)

    while index < length:
        character = normalized_sql[index]
        if character in LITERAL_DELIMITERS:
            index = _skip_literal(normalized_sql, index)
            continue
        if character == "(":
            closing_index = _find_matching_parenthesis(normalized_sql, index)
            return (
                normalized_sql[:index].strip(),
                normalized_sql[index + 1 : closing_index].strip(),
                normalized_sql[closing_index + 1 :].strip(),
            )
        index += 1

    raise ValueError(f"CREATE TABLE has no column list: {_preview(normalized_sql)}")


def render_index(index_sql: str) -> str:
    """Render a CREATE INDEX, one clause per line.

    A partial index always breaks before WHERE, and a long definition also
    breaks before the indexed column list -- the same split point the
    PostgreSQL schema uses for its USING clause.
    """
    normalized = normalize_sql(index_sql)
    where_index = _find_top_level_keyword(normalized, "WHERE")
    head = normalized if where_index is None else normalized[:where_index].rstrip()

    # The terminator lands on the head only when no WHERE clause follows it.
    head_width = len(head) + (1 if where_index is None else 0)
    lines = [head]
    if head_width > MAX_LINE_LENGTH:
        columns_index = _find_first_top_level_parenthesis(head)
        if columns_index is not None:
            lines = [head[:columns_index].rstrip(), f"{TABLE_INDENT}{head[columns_index:]}"]

    if where_index is not None:
        lines.append(f"{TABLE_INDENT}{normalized[where_index:]}")
    return _terminate("\n".join(lines))


def _find_first_top_level_parenthesis(text: str) -> int | None:
    """Return the offset of the first '(' outside any literal or nested group."""
    index, length = 0, len(text)
    while index < length:
        character = text[index]
        if character in LITERAL_DELIMITERS:
            index = _skip_literal(text, index)
            continue
        if character == "(":
            return index
        index += 1
    return None


def render_statement(statement_sql: str) -> str:
    """Render a statement that is emitted as-is (views, triggers)."""
    return _terminate(normalize_sql(statement_sql))


class SQLiteDDLExtractor:
    """Extract DDL from SQLite databases."""

    def __init__(self, connection: sqlite3.Connection) -> None:
        self.conn = connection
        self.conn.row_factory = sqlite3.Row

    def _execute_query(
        self, query: str, params: tuple[Any, ...], operation_name: str
    ) -> list[sqlite3.Row]:
        """Execute a catalog query, letting database errors fail the run.

        Converting an error into an empty result would silently omit schema
        objects from the reference DDL while the run still exits 0.
        """
        try:
            cursor = self.conn.execute(query, params)
            try:
                return cursor.fetchall()
            finally:
                cursor.close()
        except sqlite3.Error as e:
            raise RuntimeError(f"Error {operation_name}: {e}") from e

    def extract_schema(self) -> SchemaInfo:
        """Extract every schema object, with indexes and triggers grouped by table."""
        rows = self._execute_query(SCHEMA_OBJECTS_QUERY, (), "listing schema objects")

        create_statements: dict[str, str] = {}
        indexes: dict[str, list[tuple[str, str]]] = {}
        triggers: dict[str, list[tuple[str, str]]] = {}
        views: list[str] = []

        for row in rows:
            object_type, name, table_name, sql = (
                row["type"],
                row["name"],
                row["tbl_name"],
                row["sql"],
            )
            if object_type == "table":
                if VIRTUAL_TABLE_PATTERN.match(normalize_sql(sql)):
                    raise NotImplementedError(
                        f"Table {name} is a virtual table, which this generator cannot render. "
                        "Its backing shadow tables are indistinguishable from ordinary tables in "
                        "sqlite_master, so replaying the output would create them twice."
                    )
                create_statements[name] = sql
            elif object_type == "index":
                indexes.setdefault(table_name, []).append((name, sql))
            elif object_type == "trigger":
                triggers.setdefault(table_name, []).append((name, sql))
            elif object_type == "view":
                views.append(sql)
            else:
                raise NotImplementedError(
                    f"Unsupported sqlite_master object type {object_type!r} for {name}"
                )

        # An index or trigger attached to a view has no table to group under and
        # would otherwise be dropped from the output silently.
        for owner in sorted(set(indexes) | set(triggers)):
            if owner not in create_statements:
                raise NotImplementedError(
                    f"Schema objects are attached to {owner}, which is not a table. "
                    "This generator groups indexes and triggers under their table."
                )

        table_ddls = [
            TableInfo(
                table_name=name,
                create_sql=sql,
                indexes=[index_sql for _, index_sql in sorted(indexes.get(name, []))],
                triggers=[trigger_sql for _, trigger_sql in sorted(triggers.get(name, []))],
                referenced_tables=self._get_referenced_tables(name),
            )
            for name, sql in sorted(create_statements.items())
        ]

        # Sort tables based on foreign key dependencies (topological sort). Views
        # keep the query's name ordering.
        return SchemaInfo(tables=self._topological_sort_tables(table_ddls), views=views)

    def _get_referenced_tables(self, table_name: str) -> set[str]:
        """Get the tables a table's foreign keys point at."""
        rows = self._execute_query(
            'SELECT "table" AS referenced_table FROM pragma_foreign_key_list(?)',
            (table_name,),
            f"getting foreign keys for {table_name}",
        )
        return {row["referenced_table"] for row in rows}

    def _topological_sort_tables(self, table_ddls: list[TableInfo]) -> list[TableInfo]:
        """Order tables so a referenced table precedes the tables referencing it.

        Kahn's algorithm. SQLite resolves foreign keys at DML time, not DDL
        time, so replay does not depend on this order; it exists so the schema
        reads top to bottom without forward references.
        """
        dependencies: dict[str, set[str]] = {}
        table_map: dict[str, TableInfo] = {}
        known_tables = {table_info.table_name for table_info in table_ddls}

        for table_info in table_ddls:
            table_name = table_info.table_name
            table_map[table_name] = table_info
            # Self-references and references outside this schema impose no order.
            dependencies[table_name] = {
                referenced_table
                for referenced_table in table_info.referenced_tables
                if referenced_table != table_name and referenced_table in known_tables
            }

        sorted_tables: list[TableInfo] = []
        in_degree = {table: len(deps) for table, deps in dependencies.items()}
        queue = [table for table, degree in in_degree.items() if degree == 0]

        while queue:
            queue.sort()  # a fixed order among ready tables keeps output stable
            current_table = queue.pop(0)
            sorted_tables.append(table_map[current_table])

            for table_name, deps in dependencies.items():
                if current_table in deps:
                    in_degree[table_name] -= 1
                    if in_degree[table_name] == 0:
                        queue.append(table_name)

        # A cycle leaves tables unplaced. Emit them alphabetically rather than
        # failing: the order is unsatisfiable, but the DDL is still correct.
        if len(sorted_tables) != len(table_ddls):
            placed = {table_info.table_name for table_info in sorted_tables}
            remaining_tables = [table_map[name] for name in dependencies if name not in placed]
            print(
                "Warning: Circular dependencies detected, adding remaining tables in alphabetical order",
                file=sys.stderr,
            )
            remaining_tables.sort(key=lambda t: t.table_name)
            sorted_tables.extend(remaining_tables)

        return sorted_tables

    def generate_ddl(self, table_info: TableInfo) -> str:
        """Generate DDL string for a single table."""
        ddl_parts: list[str] = []

        header_line = f"Table: {quote_identifier_if_needed(table_info.table_name)}"
        ddl_parts.append(f"-- {header_line}")
        ddl_parts.append(f"-- {'-' * len(header_line)}")
        ddl_parts.append(render_create_table(table_info.create_sql))

        if table_info.indexes:
            ddl_parts.append("")
            ddl_parts.extend(render_index(index_sql) for index_sql in table_info.indexes)

        if table_info.triggers:
            ddl_parts.append("")
            ddl_parts.extend(render_statement(trigger_sql) for trigger_sql in table_info.triggers)

        return "\n".join(ddl_parts)

    def generate_schema(self, schema_info: SchemaInfo) -> str:
        """Render the complete schema artifact."""
        output = StringIO()
        output.write(SCHEMA_PREAMBLE)
        for i, table_info in enumerate(schema_info.tables):
            if i > 0:
                output.write("\n\n")
            output.write(self.generate_ddl(table_info))
            output.write("\n")

        if schema_info.views:
            if schema_info.tables:
                output.write("\n\n")
            output.write("-- Views\n")
            output.write("-- " + "=" * 30 + "\n\n")
            for i, view_sql in enumerate(schema_info.views):
                if i > 0:
                    output.write("\n")
                output.write(render_statement(view_sql))
                output.write("\n")

        return output.getvalue()


def _tuple_rows(
    connection: sqlite3.Connection, query: str, params: tuple[Any, ...] = ()
) -> list[tuple[Any, ...]]:
    """Run a query returning plain tuples, whatever row_factory the caller set.

    The extractor installs sqlite3.Row on its connection, and Row has no
    ordering, so fingerprint rows must be plain tuples to be sorted and
    compared.
    """
    cursor = connection.cursor()
    cursor.row_factory = None
    try:
        return cursor.execute(query, params).fetchall()
    finally:
        cursor.close()


def schema_fingerprint(connection: sqlite3.Connection) -> dict[str, Any]:
    """Summarize a schema the way SQLite itself reads it.

    PRAGMAs report SQLite's parse of the stored CREATE text rather than the text
    itself: a dropped ON DELETE CASCADE surfaces as on_delete='NO ACTION', and a
    UNIQUE constraint surfaces as an index object appearing nowhere in the text.
    Nothing here reuses the rendering code, so a rendering bug cannot make the
    comparison agree with itself.

    index_list.seq and foreign_key_list.id number objects in creation order and
    are dropped, since this generator reorders constraints and indexes by name;
    keeping them would report intended behavior as corruption. Position within a
    composite foreign key is meaning rather than ordering, and is kept.
    """
    fingerprint: dict[str, Any] = {}

    fingerprint["tables"] = sorted(
        _tuple_rows(
            connection,
            "SELECT name, wr, strict, ncol FROM pragma_table_list"
            " WHERE type = 'table' AND name NOT LIKE 'sqlite\\_%' ESCAPE '\\'",
        )
    )

    per_table: dict[str, Any] = {}
    for table_name, *_ in fingerprint["tables"]:
        columns = _tuple_rows(
            connection, "SELECT * FROM pragma_table_xinfo(?) ORDER BY cid", (table_name,)
        )

        foreign_keys: dict[int, tuple[Any, list[Any]]] = {}
        for (
            key_id,
            seq,
            target,
            source_col,
            target_col,
            on_update,
            on_delete,
            match,
        ) in _tuple_rows(connection, "SELECT * FROM pragma_foreign_key_list(?)", (table_name,)):
            entry = foreign_keys.setdefault(key_id, ((target, on_update, on_delete, match), []))
            entry[1].append((seq, source_col, target_col))

        indexes = sorted(
            _tuple_rows(
                connection,
                'SELECT name, "unique", origin, partial FROM pragma_index_list(?)',
                (table_name,),
            )
        )

        per_table[table_name] = {
            "columns": columns,
            "foreign_keys": sorted(
                (meta, tuple(sorted(cols))) for meta, cols in foreign_keys.values()
            ),
            "indexes": indexes,
        }
    fingerprint["per_table"] = per_table

    fingerprint["index_columns"] = {
        name: _tuple_rows(connection, "SELECT * FROM pragma_index_xinfo(?) ORDER BY seqno", (name,))
        for (name,) in _tuple_rows(
            connection, "SELECT name FROM sqlite_master WHERE type = 'index' AND sql IS NOT NULL"
        )
    }

    fingerprint["checks"] = _check_expressions(connection)
    return fingerprint


def _canonical_expression(text: str) -> str:
    """Normalize an expression so layout cannot register as a content change.

    The renderer may break a long predicate across lines, which leaves a space
    just inside the parentheses it wrapped. Dropping spaces adjacent to
    parentheses -- outside literals, where they are data -- keeps the
    fingerprint comparing what the constraint says rather than how it is set.
    """
    normalized = normalize_sql(text)
    canonical: list[str] = []
    index, length = 0, len(normalized)

    while index < length:
        character = normalized[index]
        if character in LITERAL_DELIMITERS:
            literal_end = _skip_literal(normalized, index)
            canonical.append(normalized[index:literal_end])
            index = literal_end
            continue
        if character == " ":
            previous = canonical[-1][-1] if canonical else ""
            following = normalized[index + 1] if index + 1 < length else ""
            if previous == "(" or following == ")":
                index += 1
                continue
        canonical.append(character)
        index += 1

    return "".join(canonical)


def _check_expressions(connection: sqlite3.Connection) -> list[tuple[str, str]]:
    """Collect every CHECK expression, paired with the object that declares it.

    No PRAGMA reports CHECK constraints, so they exist only in the stored text
    and this is the one part of the fingerprint that must read it. The scan is
    kept minimal -- locate the keyword, take the balanced parentheses after it
    -- so it shares none of the splitting, reordering, or requoting logic whose
    output it checks.
    """
    expressions: list[tuple[str, str]] = []

    for name, sql in _tuple_rows(
        connection, "SELECT name, sql FROM sqlite_master WHERE sql IS NOT NULL"
    ):
        index, length = 0, len(sql)
        while index < length:
            character = sql[index]
            if character in LITERAL_DELIMITERS:
                index = _skip_literal(sql, index)
                continue
            if not sql[index:].upper().startswith("CHECK") or _is_identifier_character(
                sql[index - 1] if index else " "
            ):
                index += 1
                continue
            opening = sql.find("(", index)
            if opening == -1:
                break
            closing = _find_matching_parenthesis(sql, opening)
            expressions.append((name, _canonical_expression(sql[opening + 1 : closing])))
            index = closing + 1

    return sorted(expressions)


def validate_schema(schema_sql: str, source_connection: sqlite3.Connection) -> bool:
    """Validate the generated schema against the database it was extracted from.

    Two checks, both required because they fail in different ways:

    1. Round trip. Re-extracting and re-rendering the replayed schema must
       reproduce the input byte for byte, proving the output executes and that
       rendering is a fixed point.
    2. Fidelity. SQLite's reading of the replayed schema must match its reading
       of the source. The round trip is blind to this: both its sides pass
       through the same renderer, so a clause dropped uniformly is absent from
       the replay too and still compares equal.

    Returns True only if both pass.
    """
    if not schema_sql.strip():
        print("Warning: Schema is empty", file=sys.stderr)
        return True

    print("Replaying schema into an in-memory database...")
    connection = sqlite3.connect(":memory:")
    try:
        try:
            connection.executescript(schema_sql)
        except sqlite3.Error as e:
            print(f"ERROR: Generated schema failed to execute: {e}", file=sys.stderr)
            return False

        extractor = SQLiteDDLExtractor(connection)
        replayed_sql = extractor.generate_schema(extractor.extract_schema())
        replayed_fingerprint = schema_fingerprint(connection)
    finally:
        connection.close()

    if replayed_sql != schema_sql:
        print("\n❌ Schema validation failed - the replayed schema differs", file=sys.stderr)
        _report_first_difference(schema_sql, replayed_sql)
        return False

    source_fingerprint = schema_fingerprint(source_connection)
    if replayed_fingerprint != source_fingerprint:
        print(
            "\n❌ Schema validation failed - the rebuilt database differs from the source",
            file=sys.stderr,
        )
        _report_fingerprint_difference(source_fingerprint, replayed_fingerprint)
        return False

    check_count = len(source_fingerprint["checks"])
    print(
        f"✅ Schema validation passed - replay matches exactly and rebuilds an identical "
        f"schema ({len(source_fingerprint['tables'])} tables, "
        f"{len(source_fingerprint['index_columns'])} indexes, {check_count} CHECK constraints)"
    )
    return True


def _report_fingerprint_difference(
    source_fingerprint: dict[str, Any], replayed_fingerprint: dict[str, Any]
) -> None:
    """Print the first schema aspect where source and rebuilt database disagree."""
    for aspect in ("tables", "per_table", "index_columns", "checks"):
        source_value = source_fingerprint[aspect]
        replayed_value = replayed_fingerprint[aspect]
        if source_value == replayed_value:
            continue

        if isinstance(source_value, dict):
            # Keyed aspects (per_table, index_columns) name the object that
            # differs; the annotations keep the key type sortable.
            source_map: dict[str, Any] = source_value
            replayed_map: dict[str, Any] = replayed_value
            for key in sorted(set(source_map) | set(replayed_map)):
                if source_map.get(key) != replayed_map.get(key):
                    print(f"{aspect}[{key}]:", file=sys.stderr)
                    print(f"  source: {_preview(str(source_map.get(key)))}", file=sys.stderr)
                    print(f"  rebuilt: {_preview(str(replayed_map.get(key)))}", file=sys.stderr)
                    return
        else:
            source_only = [item for item in source_value if item not in replayed_value]
            replayed_only = [item for item in replayed_value if item not in source_value]
            print(f"{aspect}:", file=sys.stderr)
            for item in source_only[:5]:
                print(f"  only in source: {_preview(str(item))}", file=sys.stderr)
            for item in replayed_only[:5]:
                print(f"  only in rebuilt: {_preview(str(item))}", file=sys.stderr)
            return


def _report_first_difference(generated_sql: str, replayed_sql: str) -> None:
    """Print the first line where the generated and replayed schemas diverge."""
    generated_lines = generated_sql.split("\n")
    replayed_lines = replayed_sql.split("\n")

    for line_number, (generated_line, replayed_line) in enumerate(
        zip(generated_lines, replayed_lines), start=1
    ):
        if generated_line != replayed_line:
            print(f"First difference at line {line_number}:", file=sys.stderr)
            print(f"  generated: {_preview(generated_line)}", file=sys.stderr)
            print(f"  replayed:  {_preview(replayed_line)}", file=sys.stderr)
            return

    print(
        f"Schemas share a common prefix but differ in length "
        f"({len(generated_lines)} vs {len(replayed_lines)} lines)",
        file=sys.stderr,
    )


@contextmanager
def ephemeral_sqlite() -> Iterator[Path]:
    """Yield a database path inside a temporary directory removed on exit."""
    with TemporaryDirectory() as temporary_directory:
        yield Path(temporary_directory) / EPHEMERAL_DATABASE_NAME


@contextmanager
def connect_read_only(database: Path) -> Iterator[sqlite3.Connection]:
    """Open a SQLite database read-only, so extraction cannot modify it."""
    if not database.is_file():
        raise FileNotFoundError(f"SQLite database not found: {database}")

    connection = sqlite3.connect(f"{database.resolve().as_uri()}?mode=ro", uri=True)
    try:
        yield connection
    finally:
        connection.close()


def run_alembic_migrations(database: Path, skip_if_failed: bool = False) -> bool:
    """Upgrade the database to head, returning whether it succeeded.

    The engine's connection is handed to Alembic through config.attributes so
    it migrates this database rather than whatever URL alembic.ini names.
    Set skip_if_failed to suppress the warnings on failure.
    """
    try:
        phoenix_db_path = Path(phoenix.db.__path__[0])
        alembic_ini = phoenix_db_path / "alembic.ini"

        if not alembic_ini.exists():
            if not skip_if_failed:
                print(
                    f"Warning: Alembic config not found at {alembic_ini}, skipping migrations",
                    file=sys.stderr,
                )
            return False

        config = Config(str(alembic_ini))
        config.set_main_option("script_location", str(phoenix_db_path / "migrations"))

        engine = create_engine(URL.create(drivername="sqlite", database=str(database)))

        print("Running Alembic migrations...")
        with engine.connect() as conn:
            config.attributes["connection"] = conn
            # Phoenix's SQLite DDL extraction reads sqlite_master directly, so
            # SQLAlchemy's inability to reflect expression indexes cannot affect
            # the generated asset. Alembic emits this warning while applying
            # migrations; suppress only that known, irrelevant reflection warning.
            with warnings.catch_warnings():
                warnings.filterwarnings(
                    "ignore",
                    message=EXPRESSION_INDEX_REFLECTION_WARNING,
                    category=SAWarning,
                )
                command.upgrade(config, "head")
        engine.dispose()
        print("Migrations completed successfully")
        return True

    except Exception as e:
        if not skip_if_failed:
            print(f"Error: Failed to run migrations: {e}", file=sys.stderr)
        return False


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Extract DDL from SQLite database (ephemeral by default, --external for existing database)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--external",
        action="store_true",
        help="Read an existing SQLite database (default: create ephemeral database)",
    )
    parser.add_argument(
        "--database", type=Path, help="Path to the SQLite database file (external mode)"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=argparse.SUPPRESS,
        help="Output file path (defaults to the canonical asset, or next to this script with --external)",
    )

    args = parser.parse_args()
    if not hasattr(args, "output"):
        args.output = EXTERNAL_OUTPUT if args.external else CANONICAL_OUTPUT

    if args.external and args.database is None:
        print("Error: External mode requires --database", file=sys.stderr)
        return 1
    if not args.external and args.database is not None:
        print("Error: --database is only valid with --external", file=sys.stderr)
        return 1

    try:
        if args.external:
            return _extract_ddl_external(args)
        else:
            return _extract_ddl_ephemeral(args)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1


def _extract_ddl_ephemeral(args: argparse.Namespace) -> int:
    """Extract DDL using an ephemeral SQLite database."""
    print("Creating ephemeral SQLite database...")

    with ephemeral_sqlite() as database:
        print(f"Database: {database}")
        if not run_alembic_migrations(database):
            return 1
        return _extract_ddl_from_database(database, args)


def _extract_ddl_external(args: argparse.Namespace) -> int:
    """Extract DDL from an existing SQLite database, leaving its schema untouched."""
    print(f"Reading external SQLite database: {args.database}")
    return _extract_ddl_from_database(args.database, args)


def _extract_ddl_from_database(database: Path, args: argparse.Namespace) -> int:
    """Extract DDL from the SQLite database at the given path."""
    with connect_read_only(database) as connection:
        print("Extracting DDL...")
        extractor = SQLiteDDLExtractor(connection)

        # Render in full before touching the destination: generation can fail on
        # unsupported schema features, and must not truncate the checked-in DDL.
        schema_info = extractor.extract_schema()
        schema_sql = extractor.generate_schema(schema_info)

        # Validate while the source is open; the fidelity check compares against
        # this schema, not just the rendered text.
        print("\nValidating schema...")
        if not validate_schema(schema_sql, connection):
            print("Error: Schema failed validation - destination was not changed", file=sys.stderr)
            return 1

    # Stage in the destination directory so the final rename is atomic and a
    # crash mid-write cannot leave a truncated schema file behind.
    temporary_output: Path | None = None
    try:
        with NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=args.output.parent,
            prefix=f".{args.output.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary_file:
            temporary_file.write(schema_sql)
            temporary_output = Path(temporary_file.name)

        temporary_output.replace(args.output)
        temporary_output = None
    except OSError as e:
        print(f"Error writing to {args.output}: {e}", file=sys.stderr)
        return 1
    finally:
        if temporary_output is not None:
            temporary_output.unlink(missing_ok=True)

    print(f"DDL exported to: {args.output}")
    print(f"Processed {len(schema_info.tables)} tables and {len(schema_info.views)} views")

    return 0


SQLITE_KEYWORDS = frozenset(
    {
        "abort",
        "action",
        "add",
        "after",
        "all",
        "alter",
        "always",
        "analyze",
        "and",
        "as",
        "asc",
        "attach",
        "autoincrement",
        "before",
        "begin",
        "between",
        "by",
        "cascade",
        "case",
        "cast",
        "check",
        "collate",
        "column",
        "commit",
        "conflict",
        "constraint",
        "create",
        "cross",
        "current",
        "current_date",
        "current_time",
        "current_timestamp",
        "database",
        "default",
        "deferrable",
        "deferred",
        "delete",
        "desc",
        "detach",
        "distinct",
        "do",
        "drop",
        "each",
        "else",
        "end",
        "escape",
        "except",
        "exclude",
        "exclusive",
        "exists",
        "explain",
        "fail",
        "filter",
        "first",
        "following",
        "for",
        "foreign",
        "from",
        "full",
        "generated",
        "glob",
        "group",
        "groups",
        "having",
        "if",
        "ignore",
        "immediate",
        "in",
        "index",
        "indexed",
        "initially",
        "inner",
        "insert",
        "instead",
        "intersect",
        "into",
        "is",
        "isnull",
        "join",
        "key",
        "last",
        "left",
        "like",
        "limit",
        "match",
        "materialized",
        "natural",
        "no",
        "not",
        "nothing",
        "notnull",
        "null",
        "nulls",
        "of",
        "offset",
        "on",
        "or",
        "order",
        "others",
        "outer",
        "over",
        "partition",
        "plan",
        "pragma",
        "preceding",
        "primary",
        "query",
        "raise",
        "range",
        "recursive",
        "references",
        "regexp",
        "reindex",
        "release",
        "rename",
        "replace",
        "restrict",
        "returning",
        "right",
        "rollback",
        "row",
        "rows",
        "savepoint",
        "select",
        "set",
        "table",
        "temp",
        "temporary",
        "then",
        "ties",
        "to",
        "transaction",
        "trigger",
        "unbounded",
        "union",
        "unique",
        "update",
        "using",
        "vacuum",
        "values",
        "view",
        "virtual",
        "when",
        "where",
        "window",
        "with",
        "without",
    }
)


if __name__ == "__main__":
    sys.exit(main())
