/**
 * Environment variables shared across phoenix packages
 */

const ENV_PHOENIX_PORT = "PHOENIX_PORT";
const ENV_PHOENIX_GRPC_PORT = "PHOENIX_GRPC_PORT";
const ENV_PHOENIX_HOST = "PHOENIX_HOST";
const ENV_PHOENIX_CLIENT_HEADERS = "PHOENIX_CLIENT_HEADERS";
const ENV_PHOENIX_COLLECTOR_ENDPOINT = "PHOENIX_COLLECTOR_ENDPOINT";
const ENV_PHOENIX_API_KEY = "PHOENIX_API_KEY";

/** Defaults for environment variables */
const DEFAULT_PHOENIX_PORT = 6006;
const DEFAULT_PHOENIX_GRPC_PORT = 4317;
const DEFAULT_PHOENIX_HOST = "0.0.0.0";
const DEFAULT_PHOENIX_CLIENT_HEADERS = {};
const DEFAULT_PHOENIX_COLLECTOR_ENDPOINT = "http://localhost:6006";
const DEFAULT_PHOENIX_API_KEY = "";

export {
  ENV_PHOENIX_PORT,
  ENV_PHOENIX_GRPC_PORT,
  ENV_PHOENIX_HOST,
  ENV_PHOENIX_CLIENT_HEADERS,
  ENV_PHOENIX_COLLECTOR_ENDPOINT,
  ENV_PHOENIX_API_KEY,
  DEFAULT_PHOENIX_PORT,
  DEFAULT_PHOENIX_GRPC_PORT,
  DEFAULT_PHOENIX_HOST,
  DEFAULT_PHOENIX_CLIENT_HEADERS,
  DEFAULT_PHOENIX_COLLECTOR_ENDPOINT,
  DEFAULT_PHOENIX_API_KEY,
};
