from asyncio import gather
from datetime import datetime, timezone
from typing import Optional

import strawberry
from sqlalchemy import and_, select
from strawberry.relay import GlobalID, Node, NodeID
from strawberry.scalars import JSON
from strawberry.types import Info

from phoenix.db import models
from phoenix.server.api.context import Context
from phoenix.server.api.exceptions import NotFound


@strawberry.type
class AgentSession(Node):
    id: NodeID[int]
    db_record: strawberry.Private[Optional[models.AgentSession]] = None

    def __post_init__(self) -> None:
        if self.db_record and self.id != self.db_record.id:
            raise ValueError("AgentSession ID mismatch")

    def _not_found(self) -> NotFound:
        global_id = GlobalID(self.__class__.__name__, str(self.id))
        return NotFound(f"Unknown agent session: {global_id}")

    async def _ensure_access(self, info: Info[Context, None]) -> None:
        if not info.context.settings.agent_assistant_enabled.enabled:
            raise self._not_found()
        if self.db_record:
            agent_session_id = self.db_record.id
            owner_id = self.db_record.user_id
            expires_at = self.db_record.expires_at
        else:
            fields = info.context.data_loaders.agent_session_fields
            agent_session_id, owner_id, expires_at = await gather(
                fields.load((self.id, models.AgentSession.id)),
                fields.load((self.id, models.AgentSession.user_id)),
                fields.load((self.id, models.AgentSession.expires_at)),
            )
        viewer_id = info.context.user_id
        if agent_session_id is None or (viewer_id is not None and owner_id != viewer_id):
            raise self._not_found()
        if expires_at is not None and expires_at <= datetime.now(timezone.utc):
            raise self._not_found()

    @strawberry.field(
        description=("The title of the session."),
    )  # type: ignore
    async def title(self, info: Info[Context, None]) -> str:
        await self._ensure_access(info)
        if self.db_record:
            return self.db_record.title
        title = await info.context.data_loaders.agent_session_fields.load(
            (self.id, models.AgentSession.title),
        )
        assert isinstance(title, str)
        return title

    @strawberry.field
    async def created_at(self, info: Info[Context, None]) -> datetime:
        await self._ensure_access(info)
        if self.db_record:
            return self.db_record.created_at
        created_at = await info.context.data_loaders.agent_session_fields.load(
            (self.id, models.AgentSession.created_at),
        )
        assert isinstance(created_at, datetime)
        return created_at

    @strawberry.field
    async def updated_at(self, info: Info[Context, None]) -> datetime:
        await self._ensure_access(info)
        if self.db_record:
            return self.db_record.updated_at
        updated_at = await info.context.data_loaders.agent_session_fields.load(
            (self.id, models.AgentSession.updated_at),
        )
        assert isinstance(updated_at, datetime)
        return updated_at

    @strawberry.field(
        description="Whether the session expires after a period of inactivity.",
    )  # type: ignore
    async def is_temporary(self, info: Info[Context, None]) -> bool:
        await self._ensure_access(info)
        if self.db_record:
            return self.db_record.expires_at is not None
        expires_at = await info.context.data_loaders.agent_session_fields.load(
            (self.id, models.AgentSession.expires_at),
        )
        return expires_at is not None

    @strawberry.field(
        description="The persisted transcript as Vercel AI UIMessage JSON objects.",
    )  # type: ignore
    async def messages(self, info: Info[Context, None]) -> JSON:
        await self._ensure_access(info)
        stmt = (
            select(models.AgentSessionMessage.message)
            .where(models.AgentSessionMessage.agent_session_id == self.id)
            .order_by(models.AgentSessionMessage.position)
        )
        async with info.context.db.read() as session:
            messages = (await session.scalars(stmt)).all()
        return JSON(
            [
                message.model_dump(mode="json", by_alias=True, exclude_none=True)
                for message in messages
            ],
        )

    @strawberry.field(
        description=(
            "The active structured summary generated by the latest conversation compaction."
        ),
    )  # type: ignore
    async def compaction_summary(
        self,
        info: Info[Context, None],
    ) -> Optional[str]:
        await self._ensure_access(info)
        stmt = select(models.AgentSessionSnapshot.compaction_summary).where(
            models.AgentSessionSnapshot.agent_session_id == self.id,
            models.AgentSessionSnapshot.compaction_event_position.is_not(None),
        )
        async with info.context.db.read() as session:
            summary = await session.scalar(stmt)
        assert summary is None or isinstance(summary, str)
        return summary

    @strawberry.field(
        description="The transcript message after which the latest compaction occurred.",
    )  # type: ignore
    async def compaction_message_id(
        self,
        info: Info[Context, None],
    ) -> Optional[str]:
        await self._ensure_access(info)
        stmt = (
            select(models.AgentSessionMessage.message_id)
            .join(
                models.AgentSessionSnapshot,
                and_(
                    models.AgentSessionSnapshot.agent_session_id
                    == models.AgentSessionMessage.agent_session_id,
                    models.AgentSessionSnapshot.compaction_event_position
                    == models.AgentSessionMessage.position,
                ),
            )
            .where(
                models.AgentSessionMessage.agent_session_id == self.id,
                models.AgentSessionSnapshot.compaction_summary.is_not(None),
            )
        )
        async with info.context.db.read() as session:
            message_id = await session.scalar(stmt)
        assert message_id is None or isinstance(message_id, str)
        return message_id


def to_gql_agent_session(agent_session: models.AgentSession) -> AgentSession:
    return AgentSession(
        id=agent_session.id,
        db_record=agent_session,
    )
