apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-datagen
  labels:
    app: phoenix-datagen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoenix-datagen
  template:
    metadata:
      labels:
        app: phoenix-datagen
    spec:
      containers:
        - name: datagen
          image: arizephoenix/phoenix:version-20.3.0
          command:
            - phoenix
            - datagen
          env:
            - name: PHOENIX_COLLECTOR_ENDPOINT
              value: http://phoenix:6006
            - name: PHOENIX_PROJECT_NAME
              value: datagen-default
            - name: PHOENIX_DATAGEN_RATE
              value: "12"
            - name: PHOENIX_DATAGEN_EPSILON
              value: "0.02"
            - name: PHOENIX_DATAGEN_SEED
              value: "0"
