import type { UIMessage } from "ai";
import { useCallback, useRef } from "react";

import { authFetch } from "@phoenix/authFetch";
import { useAgentStore } from "@phoenix/contexts/AgentContext";

async function fetchSummary({
  summarizeApiUrl,
  messages,
  ingestTraces,
  exportRemoteTraces,
}: {
  summarizeApiUrl: string;
  messages: UIMessage[];
  ingestTraces: boolean;
  exportRemoteTraces: boolean;
}): Promise<string> {
  const response = await authFetch(summarizeApiUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ messages, ingestTraces, exportRemoteTraces }),
  });
  if (!response.ok) {
    throw new Error(`summarize request failed: ${response.status}`);
  }
  const data = (await response.json()) as { summary: string };
  return data.summary.trim();
}

/**
 * Hook that provides a function to asynchronously generate a session summary
 * after the first assistant response completes.
 *
 * The summary is generated by POSTing the session's full message history to
 * the dedicated `/agent-sessions/{session_id}/summary` endpoint, which owns
 * the prompt and the structured-output tool schema. Fire-and-forget so the
 * UI never blocks on it.
 */
export function useGenerateSessionSummary({
  summarizeApiUrl,
}: {
  summarizeApiUrl: string;
}) {
  const store = useAgentStore();
  const requestedSessionsRef = useRef(new Set<string>());

  const generateSummary = useCallback(
    ({ sessionId }: { sessionId: string }) => {
      if (requestedSessionsRef.current.has(sessionId)) return;

      const state = store.getState();
      const session = state.sessionMap[sessionId];
      if (!session) return;
      if (session.shortSummary) return;
      if (session.messages.length === 0) return;

      requestedSessionsRef.current.add(sessionId);

      const hasRemoteCollector = Boolean(state.agentsConfig.collectorEndpoint);

      void fetchSummary({
        summarizeApiUrl,
        messages: session.messages,
        ingestTraces: state.observability.storeLocalTraces,
        exportRemoteTraces:
          state.observability.exportRemoteTraces && hasRemoteCollector,
      })
        .then((summary) => {
          if (summary) {
            store.getState().updateSessionSummary(sessionId, summary);
          }
        })
        .catch(() => {
          requestedSessionsRef.current.delete(sessionId);
        });
    },
    [summarizeApiUrl, store]
  );

  return { generateSummary };
}
