#!/usr/bin/env python

import argparse
import json
from pathlib import Path
from typing import Final

from phoenix.server.api.types.FilterVocabularyTerm import session_filter_vocabulary_terms

_DEFAULT_OUTPUT: Final = (
    Path(__file__).parents[1] / "js/app/src/pages/project/sessionFilterCoreVocabulary.generated.ts"
)


def _render() -> str:
    terms = session_filter_vocabulary_terms()
    lines = [
        "// This file is generated by scripts/generate_session_filter_ai_query_vocabulary.py.",
        "// Do not edit it by hand.",
        "",
        "export type SessionFilterCoreVocabularyTerm = {",
        "  readonly name: string;",
        "  readonly type: string;",
        "  readonly description: string;",
        "  readonly category: string;",
        "  readonly iterableName: string | null;",
        "};",
        "",
        "// oxfmt-ignore",
        "export const sessionFilterCoreVocabulary: SessionFilterCoreVocabularyTerm[] = [",
    ]
    for term in terms:
        lines.extend(
            [
                "  {",
                f"    name: {json.dumps(term.name)},",
                f"    type: {json.dumps(term.type)},",
                f"    description: {json.dumps(term.description)},",
                f"    category: {json.dumps(term.category)},",
                f"    iterableName: {json.dumps(term.iterable_name)},",
                "  },",
            ]
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=_DEFAULT_OUTPUT)
    args = parser.parse_args()

    expected = _render()
    if args.check:
        if not args.output.exists() or args.output.read_text() != expected:
            print(
                f"{args.output} is stale; run "
                "scripts/generate_session_filter_ai_query_vocabulary.py"
            )
            return 1
        return 0

    args.output.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
