# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping, Optional, Sequence, Union


@dataclass
class AnnotationResult:
    label: Optional[str] = None
    score: Optional[float] = None
    explanation: Optional[str] = None


@dataclass
class CategoricalAnnotationValue:
    label: str
    score: Optional[float] = None


@dataclass
class CreateExperimentRequestBody:
    name: Optional[str] = None
    description: Optional[str] = None
    metadata: Optional[Mapping[str, Any]] = None
    version_id: Optional[str] = None
    splits: Optional[Sequence[str]] = None
    repetitions: Optional[int] = 1


@dataclass
class CreateExperimentRunRequestBody:
    dataset_example_id: str
    output: Any
    repetition_number: int
    start_time: str
    end_time: str
    trace_id: Optional[str] = None
    error: Optional[str] = None


@dataclass
class CreateExperimentRunResponseBodyData:
    id: str


@dataclass
class CreateProjectRequestBody:
    name: str
    description: Optional[str] = None


@dataclass
class CreateSpansResponseBody:
    total_received: int
    total_queued: int


@dataclass
class Dataset:
    id: str
    name: str
    description: Optional[str]
    metadata: Mapping[str, Any]
    created_at: str
    updated_at: str
    example_count: int


@dataclass
class DatasetExample:
    id: str
    input: Mapping[str, Any]
    output: Mapping[str, Any]
    metadata: Mapping[str, Any]
    updated_at: str


@dataclass
class DatasetVersion:
    version_id: str
    description: Optional[str]
    metadata: Mapping[str, Any]
    created_at: str


@dataclass
class DatasetWithExampleCount:
    id: str
    name: str
    description: Optional[str]
    metadata: Mapping[str, Any]
    created_at: str
    updated_at: str
    example_count: int


@dataclass
class DeleteSessionsRequestBody:
    session_identifiers: Sequence[str]


@dataclass
class Experiment:
    id: str
    dataset_id: str
    dataset_version_id: str
    repetitions: int
    metadata: Mapping[str, Any]
    project_name: Optional[str]
    created_at: str
    updated_at: str
    example_count: int
    successful_run_count: int
    failed_run_count: int
    missing_run_count: int


@dataclass
class ExperimentEvaluationResult:
    label: Optional[str] = None
    score: Optional[float] = None
    explanation: Optional[str] = None


@dataclass
class ExperimentRun:
    dataset_example_id: str
    output: Any
    repetition_number: int
    start_time: str
    end_time: str
    id: str
    experiment_id: str
    trace_id: Optional[str] = None
    error: Optional[str] = None


@dataclass
class FreeformAnnotationConfig:
    name: str
    id: str
    type: Literal["FREEFORM"]
    description: Optional[str] = None


@dataclass
class FreeformAnnotationConfigData:
    name: str
    type: Literal["FREEFORM"]
    description: Optional[str] = None


@dataclass
class GetDatasetResponseBody:
    data: DatasetWithExampleCount


@dataclass
class GetExperimentResponseBody:
    data: Experiment


@dataclass
class IncompleteExperimentEvaluation:
    experiment_run: ExperimentRun
    dataset_example: DatasetExample
    evaluation_names: Sequence[str]


@dataclass
class IncompleteExperimentRun:
    dataset_example: DatasetExample
    repetition_numbers: Sequence[int]


@dataclass
class InsertedSessionAnnotation:
    id: str


@dataclass
class InsertedSpanAnnotation:
    id: str


@dataclass
class InsertedSpanDocumentAnnotation:
    id: str


@dataclass
class InsertedTraceAnnotation:
    id: str


@dataclass
class LDAPUser:
    id: str
    created_at: str
    updated_at: str
    email: str
    username: str
    role: Literal["SYSTEM", "ADMIN", "MEMBER", "VIEWER"]
    auth_method: Literal["LDAP"]


@dataclass
class LDAPUserData:
    email: str
    username: str
    role: Literal["SYSTEM", "ADMIN", "MEMBER", "VIEWER"]
    auth_method: Literal["LDAP"]


@dataclass
class ListDatasetExamplesData:
    dataset_id: str
    version_id: str
    examples: Sequence[DatasetExample]
    filtered_splits: Optional[Sequence[str]] = None


@dataclass
class ListDatasetExamplesResponseBody:
    data: ListDatasetExamplesData


@dataclass
class ListDatasetVersionsResponseBody:
    data: Sequence[DatasetVersion]
    next_cursor: Optional[str]


@dataclass
class ListDatasetsResponseBody:
    data: Sequence[Dataset]
    next_cursor: Optional[str]


@dataclass
class ListExperimentRunsResponseBody:
    data: Sequence[ExperimentRun]
    next_cursor: Optional[str]


@dataclass
class ListExperimentsResponseBody:
    data: Sequence[Experiment]
    next_cursor: Optional[str]


@dataclass
class LocalUser:
    id: str
    created_at: str
    updated_at: str
    email: str
    username: str
    role: Literal["SYSTEM", "ADMIN", "MEMBER", "VIEWER"]
    password_needs_reset: bool
    auth_method: Literal["LOCAL"]
    password: Optional[str] = None


@dataclass
class LocalUserData:
    email: str
    username: str
    role: Literal["SYSTEM", "ADMIN", "MEMBER", "VIEWER"]
    auth_method: Literal["LOCAL"]
    password: Optional[str] = None


@dataclass
class OAuth2User:
    id: str
    created_at: str
    updated_at: str
    email: str
    username: str
    role: Literal["SYSTEM", "ADMIN", "MEMBER", "VIEWER"]
    auth_method: Literal["OAUTH2"]
    oauth2_client_id: Optional[str] = None
    oauth2_user_id: Optional[str] = None
    profile_picture_url: Optional[str] = None


@dataclass
class OAuth2UserData:
    email: str
    username: str
    role: Literal["SYSTEM", "ADMIN", "MEMBER", "VIEWER"]
    auth_method: Literal["OAUTH2"]
    oauth2_client_id: Optional[str] = None
    oauth2_user_id: Optional[str] = None


@dataclass
class OtlpStatus:
    code: Optional[int] = None
    message: Optional[str] = None


@dataclass
class Project:
    name: str
    id: str
    description: Optional[str] = None


@dataclass
class Prompt:
    name: str
    id: str
    description: Optional[str] = None
    source_prompt_id: Optional[str] = None
    metadata: Optional[Mapping[str, Any]] = None


@dataclass
class PromptAnthropicThinkingConfigDisabled:
    type: Literal["disabled"]


@dataclass
class PromptAnthropicThinkingConfigEnabled:
    budget_tokens: int
    type: Literal["enabled"]


@dataclass
class PromptAwsInvocationParametersContent:
    max_tokens: Optional[int] = None
    temperature: Optional[float] = None
    top_p: Optional[float] = None


@dataclass
class PromptAzureOpenAIInvocationParametersContent:
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    max_completion_tokens: Optional[int] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    top_p: Optional[float] = None
    seed: Optional[int] = None
    reasoning_effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None


@dataclass
class PromptCerebrasInvocationParametersContent:
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    max_completion_tokens: Optional[int] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    top_p: Optional[float] = None
    seed: Optional[int] = None
    reasoning_effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None


@dataclass
class PromptData:
    name: str
    description: Optional[str] = None
    source_prompt_id: Optional[str] = None
    metadata: Optional[Mapping[str, Any]] = None


@dataclass
class PromptDeepSeekInvocationParametersContent:
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    max_completion_tokens: Optional[int] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    top_p: Optional[float] = None
    seed: Optional[int] = None
    reasoning_effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None


@dataclass
class PromptFireworksInvocationParametersContent:
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    max_completion_tokens: Optional[int] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    top_p: Optional[float] = None
    seed: Optional[int] = None
    reasoning_effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None


@dataclass
class PromptGoogleInvocationParametersContent:
    temperature: Optional[float] = None
    max_output_tokens: Optional[int] = None
    stop_sequences: Optional[Sequence[str]] = None
    presence_penalty: Optional[float] = None
    frequency_penalty: Optional[float] = None
    top_p: Optional[float] = None
    top_k: Optional[int] = None


@dataclass
class PromptGroqInvocationParametersContent:
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    max_completion_tokens: Optional[int] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    top_p: Optional[float] = None
    seed: Optional[int] = None
    reasoning_effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None


@dataclass
class PromptMoonshotInvocationParametersContent:
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    max_completion_tokens: Optional[int] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    top_p: Optional[float] = None
    seed: Optional[int] = None
    reasoning_effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None


@dataclass
class PromptOllamaInvocationParametersContent:
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    max_completion_tokens: Optional[int] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    top_p: Optional[float] = None
    seed: Optional[int] = None
    reasoning_effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None


@dataclass
class PromptOpenAIInvocationParametersContent:
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    max_completion_tokens: Optional[int] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    top_p: Optional[float] = None
    seed: Optional[int] = None
    reasoning_effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None


@dataclass
class PromptPerplexityInvocationParametersContent:
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    max_completion_tokens: Optional[int] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    top_p: Optional[float] = None
    seed: Optional[int] = None
    reasoning_effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None


@dataclass
class PromptResponseFormatJSONSchemaDefinition:
    name: str
    description: Optional[str] = None
    schema_: Optional[Mapping[str, Any]] = None
    strict: Optional[bool] = None


@dataclass
class PromptStringTemplate:
    template: str
    type: Literal["string"]


@dataclass
class PromptTogetherInvocationParametersContent:
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    max_completion_tokens: Optional[int] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    top_p: Optional[float] = None
    seed: Optional[int] = None
    reasoning_effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None


@dataclass
class PromptToolChoiceNone:
    type: Literal["none"]


@dataclass
class PromptToolChoiceOneOrMore:
    type: Literal["one_or_more"]


@dataclass
class PromptToolChoiceSpecificFunctionTool:
    function_name: str
    type: Literal["specific_function"]


@dataclass
class PromptToolChoiceZeroOrMore:
    type: Literal["zero_or_more"]


@dataclass
class PromptToolFunctionDefinition:
    name: str
    description: Optional[str] = None
    parameters: Optional[Mapping[str, Any]] = None
    strict: Optional[bool] = None


@dataclass
class PromptVersionTag:
    name: str
    id: str
    description: Optional[str] = None


@dataclass
class PromptVersionTagData:
    name: str
    description: Optional[str] = None


@dataclass
class PromptXAIInvocationParametersContent:
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    max_completion_tokens: Optional[int] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None
    top_p: Optional[float] = None
    seed: Optional[int] = None
    reasoning_effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None


@dataclass
class SessionAnnotation:
    id: str
    created_at: str
    updated_at: str
    source: Literal["API", "APP"]
    user_id: Optional[str]
    name: str
    annotator_kind: Literal["LLM", "CODE", "HUMAN"]
    session_id: str
    result: Optional[AnnotationResult] = None
    metadata: Optional[Mapping[str, Any]] = None
    identifier: Optional[str] = ""


@dataclass
class SessionAnnotationData:
    name: str
    annotator_kind: Literal["LLM", "CODE", "HUMAN"]
    session_id: str
    result: Optional[AnnotationResult] = None
    metadata: Optional[Mapping[str, Any]] = None
    identifier: Optional[str] = ""


@dataclass
class SessionAnnotationsResponseBody:
    data: Sequence[SessionAnnotation]
    next_cursor: Optional[str]


@dataclass
class SessionTraceData:
    id: str
    trace_id: str
    start_time: str
    end_time: str


@dataclass
class SpanAnnotation:
    id: str
    created_at: str
    updated_at: str
    source: Literal["API", "APP"]
    user_id: Optional[str]
    name: str
    annotator_kind: Literal["LLM", "CODE", "HUMAN"]
    span_id: str
    result: Optional[AnnotationResult] = None
    metadata: Optional[Mapping[str, Any]] = None
    identifier: Optional[str] = ""


@dataclass
class SpanAnnotationData:
    name: str
    annotator_kind: Literal["LLM", "CODE", "HUMAN"]
    span_id: str
    result: Optional[AnnotationResult] = None
    metadata: Optional[Mapping[str, Any]] = None
    identifier: Optional[str] = ""


@dataclass
class SpanAnnotationsResponseBody:
    data: Sequence[SpanAnnotation]
    next_cursor: Optional[str]


@dataclass
class SpanContext:
    trace_id: str
    span_id: str


@dataclass
class SpanDocumentAnnotationData:
    name: str
    annotator_kind: Literal["LLM", "CODE", "HUMAN"]
    span_id: str
    document_position: int
    result: Optional[AnnotationResult] = None
    metadata: Optional[Mapping[str, Any]] = None
    identifier: Optional[str] = ""


@dataclass
class SpanEvent:
    name: str
    timestamp: str
    attributes: Optional[Mapping[str, Any]] = None


@dataclass
class SpanNoteData:
    span_id: str
    note: str


@dataclass
class TextContentPart:
    text: str
    type: Literal["text"]


@dataclass
class ToolCallFunction:
    name: str
    arguments: str
    type: Literal["function"]


@dataclass
class ToolResultContentPart:
    tool_call_id: str
    tool_result: Optional[Union[bool, int, float, str, Mapping[str, Any], Sequence[Any]]]
    type: Literal["tool_result"]


@dataclass
class TraceAnnotation:
    id: str
    created_at: str
    updated_at: str
    source: Literal["API", "APP"]
    user_id: Optional[str]
    name: str
    annotator_kind: Literal["LLM", "CODE", "HUMAN"]
    trace_id: str
    result: Optional[AnnotationResult] = None
    metadata: Optional[Mapping[str, Any]] = None
    identifier: Optional[str] = ""


@dataclass
class TraceAnnotationData:
    name: str
    annotator_kind: Literal["LLM", "CODE", "HUMAN"]
    trace_id: str
    result: Optional[AnnotationResult] = None
    metadata: Optional[Mapping[str, Any]] = None
    identifier: Optional[str] = ""


@dataclass
class TraceAnnotationsResponseBody:
    data: Sequence[TraceAnnotation]
    next_cursor: Optional[str]


@dataclass
class UpdateProjectRequestBody:
    description: Optional[str] = None


@dataclass
class UpdateProjectResponseBody:
    data: Project


@dataclass
class UploadDatasetData:
    dataset_id: str
    version_id: str


@dataclass
class UploadDatasetResponseBody:
    data: UploadDatasetData


@dataclass
class UpsertExperimentEvaluationRequestBody:
    experiment_run_id: str
    name: str
    annotator_kind: Literal["LLM", "CODE", "HUMAN"]
    start_time: str
    end_time: str
    result: Optional[ExperimentEvaluationResult] = None
    error: Optional[str] = None
    metadata: Optional[Mapping[str, Any]] = None
    trace_id: Optional[str] = None


@dataclass
class UpsertExperimentEvaluationResponseBodyData:
    id: str


@dataclass
class ValidationError:
    loc: Sequence[Union[str, int]]
    msg: str
    type: str
    input: Optional[Any] = None
    ctx: Optional[Mapping[str, Any]] = None


@dataclass
class AnnotateSessionsRequestBody:
    data: Sequence[SessionAnnotationData]


@dataclass
class AnnotateSessionsResponseBody:
    data: Sequence[InsertedSessionAnnotation]


@dataclass
class AnnotateSpanDocumentsRequestBody:
    data: Sequence[SpanDocumentAnnotationData]


@dataclass
class AnnotateSpanDocumentsResponseBody:
    data: Sequence[InsertedSpanDocumentAnnotation]


@dataclass
class AnnotateSpansRequestBody:
    data: Sequence[SpanAnnotationData]


@dataclass
class AnnotateSpansResponseBody:
    data: Sequence[InsertedSpanAnnotation]


@dataclass
class AnnotateTracesRequestBody:
    data: Sequence[TraceAnnotationData]


@dataclass
class AnnotateTracesResponseBody:
    data: Sequence[InsertedTraceAnnotation]


@dataclass
class CategoricalAnnotationConfig:
    name: str
    optimization_direction: Literal["MINIMIZE", "MAXIMIZE", "NONE"]
    values: Sequence[CategoricalAnnotationValue]
    id: str
    type: Literal["CATEGORICAL"]
    description: Optional[str] = None


@dataclass
class CategoricalAnnotationConfigData:
    name: str
    optimization_direction: Literal["MINIMIZE", "MAXIMIZE", "NONE"]
    values: Sequence[CategoricalAnnotationValue]
    type: Literal["CATEGORICAL"]
    description: Optional[str] = None


@dataclass
class ContinuousAnnotationConfig:
    name: str
    optimization_direction: Literal["MINIMIZE", "MAXIMIZE", "NONE"]
    id: str
    type: Literal["CONTINUOUS"]
    description: Optional[str] = None
    lower_bound: Optional[float] = None
    upper_bound: Optional[float] = None


@dataclass
class ContinuousAnnotationConfigData:
    name: str
    optimization_direction: Literal["MINIMIZE", "MAXIMIZE", "NONE"]
    type: Literal["CONTINUOUS"]
    description: Optional[str] = None
    lower_bound: Optional[float] = None
    upper_bound: Optional[float] = None


CreateAnnotationConfigData = Union[
    CategoricalAnnotationConfigData,
    ContinuousAnnotationConfigData,
    FreeformAnnotationConfigData,
]


@dataclass
class CreateAnnotationConfigResponseBody:
    data: Union[
        CategoricalAnnotationConfig,
        ContinuousAnnotationConfig,
        FreeformAnnotationConfig,
    ]


@dataclass
class CreateExperimentResponseBody:
    data: Experiment


@dataclass
class CreateExperimentRunResponseBody:
    data: CreateExperimentRunResponseBodyData


@dataclass
class CreateProjectResponseBody:
    data: Project


@dataclass
class CreateSpanNoteRequestBody:
    data: SpanNoteData


@dataclass
class CreateSpanNoteResponseBody:
    data: InsertedSpanAnnotation


@dataclass
class CreateUserRequestBody:
    user: Union[LocalUserData, OAuth2UserData, LDAPUserData]
    send_welcome_email: Optional[bool] = True


@dataclass
class CreateUserResponseBody:
    data: Union[LocalUser, OAuth2User, LDAPUser]


@dataclass
class DeleteAnnotationConfigResponseBody:
    data: Union[
        CategoricalAnnotationConfig,
        ContinuousAnnotationConfig,
        FreeformAnnotationConfig,
    ]


@dataclass
class GetAnnotationConfigResponseBody:
    data: Union[
        CategoricalAnnotationConfig,
        ContinuousAnnotationConfig,
        FreeformAnnotationConfig,
    ]


@dataclass
class GetAnnotationConfigsResponseBody:
    data: Sequence[
        Union[
            CategoricalAnnotationConfig,
            ContinuousAnnotationConfig,
            FreeformAnnotationConfig,
        ]
    ]
    next_cursor: Optional[str]


@dataclass
class GetIncompleteEvaluationsResponseBody:
    data: Sequence[IncompleteExperimentEvaluation]
    next_cursor: Optional[str]


@dataclass
class GetIncompleteExperimentRunsResponseBody:
    data: Sequence[IncompleteExperimentRun]
    next_cursor: Optional[str]


@dataclass
class GetProjectResponseBody:
    data: Project


@dataclass
class GetProjectsResponseBody:
    data: Sequence[Project]
    next_cursor: Optional[str]


@dataclass
class GetPromptVersionTagsResponseBody:
    data: Sequence[PromptVersionTag]
    next_cursor: Optional[str]


@dataclass
class GetPromptsResponseBody:
    data: Sequence[Prompt]
    next_cursor: Optional[str]


@dataclass
class GetUsersResponseBody:
    data: Sequence[Union[LocalUser, OAuth2User, LDAPUser]]
    next_cursor: Optional[str]


@dataclass
class HTTPValidationError:
    detail: Optional[Sequence[ValidationError]] = None


@dataclass
class PromptAnthropicInvocationParametersContent:
    max_tokens: int
    temperature: Optional[float] = None
    top_p: Optional[float] = None
    stop_sequences: Optional[Sequence[str]] = None
    thinking: Optional[
        Union[PromptAnthropicThinkingConfigDisabled, PromptAnthropicThinkingConfigEnabled]
    ] = None


@dataclass
class PromptAwsInvocationParameters:
    aws: PromptAwsInvocationParametersContent
    type: Literal["aws"]


@dataclass
class PromptAzureOpenAIInvocationParameters:
    azure_openai: PromptAzureOpenAIInvocationParametersContent
    type: Literal["azure_openai"]


@dataclass
class PromptCerebrasInvocationParameters:
    cerebras: PromptCerebrasInvocationParametersContent
    type: Literal["cerebras"]


@dataclass
class PromptDeepSeekInvocationParameters:
    deepseek: PromptDeepSeekInvocationParametersContent
    type: Literal["deepseek"]


@dataclass
class PromptFireworksInvocationParameters:
    fireworks: PromptFireworksInvocationParametersContent
    type: Literal["fireworks"]


@dataclass
class PromptGoogleInvocationParameters:
    google: PromptGoogleInvocationParametersContent
    type: Literal["google"]


@dataclass
class PromptGroqInvocationParameters:
    groq: PromptGroqInvocationParametersContent
    type: Literal["groq"]


@dataclass
class PromptMoonshotInvocationParameters:
    moonshot: PromptMoonshotInvocationParametersContent
    type: Literal["moonshot"]


@dataclass
class PromptOllamaInvocationParameters:
    ollama: PromptOllamaInvocationParametersContent
    type: Literal["ollama"]


@dataclass
class PromptOpenAIInvocationParameters:
    openai: PromptOpenAIInvocationParametersContent
    type: Literal["openai"]


@dataclass
class PromptPerplexityInvocationParameters:
    perplexity: PromptPerplexityInvocationParametersContent
    type: Literal["perplexity"]


@dataclass
class PromptResponseFormatJSONSchema:
    json_schema: PromptResponseFormatJSONSchemaDefinition
    type: str = "json_schema"


@dataclass
class PromptTogetherInvocationParameters:
    together: PromptTogetherInvocationParametersContent
    type: Literal["together"]


@dataclass
class PromptToolFunction:
    function: PromptToolFunctionDefinition
    type: str = "function"


@dataclass
class PromptTools:
    tools: Sequence[PromptToolFunction]
    type: str = "tools"
    tool_choice: Optional[
        Union[
            PromptToolChoiceNone,
            PromptToolChoiceZeroOrMore,
            PromptToolChoiceOneOrMore,
            PromptToolChoiceSpecificFunctionTool,
        ]
    ] = None
    disable_parallel_tool_calls: Optional[bool] = None


@dataclass
class PromptXAIInvocationParameters:
    xai: PromptXAIInvocationParametersContent
    type: Literal["xai"]


@dataclass
class SessionData:
    id: str
    session_id: str
    project_id: str
    start_time: str
    end_time: str
    traces: Sequence[SessionTraceData]


@dataclass
class Span:
    name: str
    context: SpanContext
    span_kind: str
    start_time: str
    end_time: str
    status_code: str
    id: Optional[str] = ""
    parent_id: Optional[str] = None
    status_message: Optional[str] = ""
    attributes: Optional[Mapping[str, Any]] = None
    events: Optional[Sequence[SpanEvent]] = None


@dataclass
class SpansResponseBody:
    data: Sequence[Span]
    next_cursor: Optional[str]


@dataclass
class ToolCallContentPart:
    tool_call_id: str
    tool_call: ToolCallFunction
    type: Literal["tool_call"]


@dataclass
class UpdateAnnotationConfigResponseBody:
    data: Union[
        CategoricalAnnotationConfig,
        ContinuousAnnotationConfig,
        FreeformAnnotationConfig,
    ]


@dataclass
class UpsertExperimentEvaluationResponseBody:
    data: UpsertExperimentEvaluationResponseBodyData


@dataclass
class CreateSpansRequestBody:
    data: Sequence[Span]


@dataclass
class GetSessionResponseBody:
    data: SessionData


@dataclass
class GetSessionsResponseBody:
    data: Sequence[SessionData]
    next_cursor: Optional[str]


@dataclass
class PromptAnthropicInvocationParameters:
    anthropic: PromptAnthropicInvocationParametersContent
    type: Literal["anthropic"]


@dataclass
class PromptMessage:
    role: Literal["user", "assistant", "model", "ai", "tool", "system", "developer"]
    content: Union[
        str,
        Sequence[Union[TextContentPart, ToolCallContentPart, ToolResultContentPart]],
    ]


@dataclass
class PromptChatTemplate:
    messages: Sequence[PromptMessage]
    type: Literal["chat"]


@dataclass
class PromptVersion:
    model_provider: Literal[
        "OPENAI",
        "AZURE_OPENAI",
        "ANTHROPIC",
        "GOOGLE",
        "DEEPSEEK",
        "XAI",
        "OLLAMA",
        "AWS",
        "CEREBRAS",
        "FIREWORKS",
        "GROQ",
        "MOONSHOT",
        "PERPLEXITY",
        "TOGETHER",
    ]
    model_name: str
    template: Union[PromptChatTemplate, PromptStringTemplate]
    template_type: Literal["STR", "CHAT"]
    template_format: Literal["MUSTACHE", "F_STRING", "NONE"]
    invocation_parameters: Union[
        PromptOpenAIInvocationParameters,
        PromptAzureOpenAIInvocationParameters,
        PromptAnthropicInvocationParameters,
        PromptGoogleInvocationParameters,
        PromptDeepSeekInvocationParameters,
        PromptXAIInvocationParameters,
        PromptOllamaInvocationParameters,
        PromptAwsInvocationParameters,
        PromptCerebrasInvocationParameters,
        PromptFireworksInvocationParameters,
        PromptGroqInvocationParameters,
        PromptMoonshotInvocationParameters,
        PromptPerplexityInvocationParameters,
        PromptTogetherInvocationParameters,
    ]
    id: str
    description: Optional[str] = None
    tools: Optional[PromptTools] = None
    response_format: Optional[PromptResponseFormatJSONSchema] = None


@dataclass
class PromptVersionData:
    model_provider: Literal[
        "OPENAI",
        "AZURE_OPENAI",
        "ANTHROPIC",
        "GOOGLE",
        "DEEPSEEK",
        "XAI",
        "OLLAMA",
        "AWS",
        "CEREBRAS",
        "FIREWORKS",
        "GROQ",
        "MOONSHOT",
        "PERPLEXITY",
        "TOGETHER",
    ]
    model_name: str
    template: Union[PromptChatTemplate, PromptStringTemplate]
    template_type: Literal["STR", "CHAT"]
    template_format: Literal["MUSTACHE", "F_STRING", "NONE"]
    invocation_parameters: Union[
        PromptOpenAIInvocationParameters,
        PromptAzureOpenAIInvocationParameters,
        PromptAnthropicInvocationParameters,
        PromptGoogleInvocationParameters,
        PromptDeepSeekInvocationParameters,
        PromptXAIInvocationParameters,
        PromptOllamaInvocationParameters,
        PromptAwsInvocationParameters,
        PromptCerebrasInvocationParameters,
        PromptFireworksInvocationParameters,
        PromptGroqInvocationParameters,
        PromptMoonshotInvocationParameters,
        PromptPerplexityInvocationParameters,
        PromptTogetherInvocationParameters,
    ]
    description: Optional[str] = None
    tools: Optional[PromptTools] = None
    response_format: Optional[PromptResponseFormatJSONSchema] = None


@dataclass
class CreatePromptRequestBody:
    prompt: PromptData
    version: PromptVersionData


@dataclass
class CreatePromptResponseBody:
    data: PromptVersion


@dataclass
class GetPromptResponseBody:
    data: PromptVersion


@dataclass
class GetPromptVersionsResponseBody:
    data: Sequence[PromptVersion]
    next_cursor: Optional[str]


@dataclass
class OtlpAnyValue:
    array_value: Optional[OtlpArrayValue] = None
    bool_value: Optional[bool] = None
    bytes_value: Optional[str] = None
    double_value: Optional[Union[float, str, Literal["Infinity", "-Infinity", "NaN"]]] = None
    int_value: Optional[Union[int, str]] = None
    kvlist_value: None = None
    string_value: Optional[str] = None


@dataclass
class OtlpArrayValue:
    values: Optional[Sequence[OtlpAnyValue]] = None


@dataclass
class OtlpEvent:
    attributes: Optional[Sequence[OtlpKeyValue]] = None
    dropped_attributes_count: Optional[int] = None
    name: Optional[str] = None
    time_unix_nano: Optional[Union[int, str]] = None


@dataclass
class OtlpKeyValue:
    key: Optional[str] = None
    value: Optional[OtlpAnyValue] = None


@dataclass
class OtlpSpan:
    attributes: Optional[Sequence[OtlpKeyValue]] = None
    dropped_attributes_count: Optional[int] = None
    dropped_events_count: Optional[int] = None
    dropped_links_count: Optional[int] = None
    end_time_unix_nano: Optional[Union[int, str]] = None
    events: Optional[Sequence[OtlpEvent]] = None
    flags: Optional[int] = None
    kind: Optional[
        Union[
            int,
            Literal[
                "SPAN_KIND_UNSPECIFIED",
                "SPAN_KIND_INTERNAL",
                "SPAN_KIND_SERVER",
                "SPAN_KIND_CLIENT",
                "SPAN_KIND_PRODUCER",
                "SPAN_KIND_CONSUMER",
            ],
        ]
    ] = "SPAN_KIND_INTERNAL"
    links: None = None
    name: Optional[str] = None
    parent_span_id: Optional[str] = None
    span_id: Optional[str] = None
    start_time_unix_nano: Optional[Union[int, str]] = None
    status: Optional[OtlpStatus] = None
    trace_id: Optional[str] = None
    trace_state: Optional[str] = None


@dataclass
class OtlpSpansResponseBody:
    data: Sequence[OtlpSpan]
    next_cursor: Optional[str]
