# Example values file demonstrating OAuth2/OIDC configuration
# This file shows how to configure multiple OAuth2 identity providers

# Enable authentication
auth:
  enableAuth: true
  useSecureCookies: true  # Recommended when using HTTPS
  
  # Configure CORS and CSRF for OAuth2
  allowedOrigins:
    - "https://your-phoenix-domain.com"
    - "https://www.your-phoenix-domain.com"
  csrfTrustedOrigins:
    - "https://your-phoenix-domain.com"
    - "https://www.your-phoenix-domain.com"
  
  # OAuth2/OIDC Configuration
  oauth2:
    enabled: true
    providers:
      # Google OAuth2 Configuration
      google:
        client_id: "your-google-client-id.apps.googleusercontent.com"
        client_secret: "your-google-client-secret"
        oidc_config_url: "https://accounts.google.com/.well-known/openid-configuration"
        display_name: "Google"
        allow_sign_up: true
        auto_login: false
      
      # AWS Cognito Configuration
      aws_cognito:
        client_id: "your-aws-cognito-client-id"
        client_secret: "your-aws-cognito-client-secret"
        oidc_config_url: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_xxxxx/.well-known/openid-configuration"
        display_name: "AWS Cognito"
        allow_sign_up: true
        auto_login: false
      
      # Microsoft Entra ID Configuration
      microsoft_entra_id:
        client_id: "your-microsoft-entra-id-client-id"
        client_secret: "your-microsoft-entra-id-client-secret"
        oidc_config_url: "https://login.microsoftonline.com/your-tenant-id/v2.0/.well-known/openid-configuration"
        display_name: "Microsoft Entra ID"
        allow_sign_up: true
        auto_login: false
      
      # Keycloak Configuration
      keycloak:
        client_id: "phoenix"
        client_secret: "your-keycloak-client-secret"
        oidc_config_url: "https://your-keycloak-server/realms/your-realm/.well-known/openid-configuration"
        display_name: "Keycloak"
        allow_sign_up: true
        auto_login: false
      
      # Auth0 Configuration (example of custom provider)
      auth0:
        client_id: "your-auth0-client-id"
        client_secret: "your-auth0-client-secret"
        oidc_config_url: "https://your-tenant.auth0.com/.well-known/openid-configuration"
        display_name: "Auth0"
        allow_sign_up: true
        auto_login: false

# Server configuration
server:
  rootUrl: "https://your-phoenix-domain.com"
  hostRootPath: ""  # Set this if Phoenix is deployed under a subpath

# Ingress configuration for HTTPS
ingress:
  enabled: true
  host: "your-phoenix-domain.com"
  tls:
    enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

# Database configuration (using external PostgreSQL)
postgresql:
  enabled: false

database:
  url: "postgresql://username:password@your-postgres-host:5432/phoenix"

# Resource configuration
resources:
  limits:
    cpu: "2000m"
    memory: "4Gi"
  requests:
    cpu: "1000m"
    memory: "2Gi"

# Security context (recommended for production)
securityContext:
  pod:
    enabled: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532
  container:
    enabled: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL