apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: phoenix
spec:
    replicas: 1
    selector:
        matchLabels:
            app: phoenix
    template:
        metadata:
            annotations:
                prometheus.io/path: /metrics
                prometheus.io/port: "9090"
                prometheus.io/scrape: "true"
            labels:
                app: phoenix
        spec:
            containers:
                - args:
                      - -m
                      - phoenix.server.main
                      - serve
                  command:
                      - python
                  env:
                      - name: PHOENIX_WORKING_DIR
                        value: /mnt/data
                      - name: PHOENIX_PORT
                        value: "6006"
                      - name: PHOENIX_SQL_DATABASE_URL
                        value: "postgresql://postgres:postgres123@postgres:5432/postgres"
<<<<<<< HEAD
                  image: arizephoenix/phoenix:version-8.32.1
=======
                  image: arizephoenix/phoenix:version-10.7.0
>>>>>>> 1003568f2ab904086ac7112124c58839b2411d50
                  name: phoenix
                  ports:
                      - containerPort: 6006
                      - containerPort: 9090
                      - containerPort: 4317
                  readinessProbe:
                      httpGet:
                          port: 6006 # readiness probe on root of application port to guarantee app is really serving before becoming ready in kubernetes
