version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: packages/phoenix-client/docs/source/conf.py

python:
  install:
    - requirements: packages/phoenix-client/docs/requirements.txt 