-- Generated by `make schema-ddl`; do not edit manually.

-- Table: alembic_version
-- ----------------------
CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);


-- Table: annotation_configs
-- -------------------------
CREATE TABLE annotation_configs (
    id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    config JSONB NOT NULL,
    CONSTRAINT pk_annotation_configs PRIMARY KEY (id),
    CONSTRAINT uq_annotation_configs_name UNIQUE (name)
);


-- Table: generative_models
-- ------------------------
CREATE TABLE generative_models (
    id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    provider VARCHAR NOT NULL,
    name_pattern VARCHAR NOT NULL,
    is_built_in BOOLEAN NOT NULL,
    start_time TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT pk_generative_models PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_generative_models_match_criteria ON generative_models
    (name_pattern, provider, is_built_in)
    WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX ix_generative_models_name_is_built_in ON generative_models
    (name, is_built_in)
    WHERE deleted_at IS NULL;
CREATE INDEX ix_generative_models_updated_at ON generative_models (updated_at);


-- Table: languages
-- ----------------
CREATE TABLE languages (
    name VARCHAR NOT NULL,
    CONSTRAINT pk_languages PRIMARY KEY (name)
);


-- Table: oauth2_clients
-- ---------------------
CREATE TABLE oauth2_clients (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    client_id VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    logo_uri VARCHAR,
    redirect_uris JSONB NOT NULL,
    grant_types JSONB NOT NULL,
    token_endpoint_auth_method VARCHAR NOT NULL,
    is_first_party BOOLEAN DEFAULT 0 NOT NULL,
    metadata JSONB,
    registration_client_ip VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX ix_oauth2_clients_client_id ON oauth2_clients (client_id);
CREATE INDEX ix_oauth2_clients_registration_client_ip ON oauth2_clients
    (registration_client_ip, created_at);


-- Table: project_trace_retention_policies
-- ---------------------------------------
CREATE TABLE project_trace_retention_policies (
    id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    cron_expression VARCHAR NOT NULL,
    rule JSONB NOT NULL,
    CONSTRAINT pk_project_trace_retention_policies PRIMARY KEY (id)
);


-- Table: projects
-- ---------------
CREATE TABLE projects (
    id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    gradient_start_color VARCHAR DEFAULT '#5bdbff' NOT NULL,
    gradient_end_color VARCHAR DEFAULT '#1c76fc' NOT NULL,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    trace_retention_policy_id INTEGER,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT uq_projects_name UNIQUE (name),
    CONSTRAINT fk_projects_trace_retention_policy_id_project_trace_retention_policies
        FOREIGN KEY (trace_retention_policy_id)
        REFERENCES project_trace_retention_policies (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_projects_trace_retention_policy_id ON projects
    (trace_retention_policy_id);


-- Table: project_annotation_configs
-- ---------------------------------
CREATE TABLE project_annotation_configs (
    id INTEGER NOT NULL,
    project_id INTEGER NOT NULL,
    annotation_config_id INTEGER NOT NULL,
    CONSTRAINT pk_project_annotation_configs PRIMARY KEY (id),
    CONSTRAINT uq_project_annotation_configs_project_id_annotation_config_id
        UNIQUE (project_id, annotation_config_id),
    CONSTRAINT fk_project_annotation_configs_annotation_config_id_annotation_configs
        FOREIGN KEY (annotation_config_id)
        REFERENCES annotation_configs (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_project_annotation_configs_project_id_projects
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_project_annotation_configs_annotation_config_id ON project_annotation_configs
    (annotation_config_id);


-- Table: project_sessions
-- -----------------------
CREATE TABLE project_sessions (
    id INTEGER NOT NULL,
    session_id VARCHAR NOT NULL,
    project_id INTEGER NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    CONSTRAINT pk_project_sessions PRIMARY KEY (id),
    CONSTRAINT uq_project_sessions_session_id UNIQUE (session_id),
    CONSTRAINT fk_project_sessions_project_id_projects
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_project_sessions_project_id_end_time ON project_sessions
    (project_id, end_time DESC);
CREATE INDEX ix_project_sessions_project_id_start_time ON project_sessions
    (project_id, start_time DESC);


-- Table: prompt_labels
-- --------------------
CREATE TABLE prompt_labels (
    id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    color VARCHAR,
    CONSTRAINT pk_prompt_labels PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_prompt_labels_name ON prompt_labels (name);


-- Table: prompts
-- --------------
CREATE TABLE prompts (
    id INTEGER NOT NULL,
    source_prompt_id INTEGER,
    name VARCHAR NOT NULL,
    description VARCHAR,
    metadata JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_prompts PRIMARY KEY (id),
    CONSTRAINT fk_prompts_source_prompt_id_prompts
        FOREIGN KEY (source_prompt_id)
        REFERENCES prompts (id)
        ON DELETE SET NULL
);

CREATE UNIQUE INDEX ix_prompts_name ON prompts (name);
CREATE INDEX ix_prompts_source_prompt_id ON prompts (source_prompt_id);


-- Table: prompts_prompt_labels
-- ----------------------------
CREATE TABLE prompts_prompt_labels (
    id INTEGER NOT NULL,
    prompt_label_id INTEGER NOT NULL,
    prompt_id INTEGER NOT NULL,
    CONSTRAINT pk_prompts_prompt_labels PRIMARY KEY (id),
    CONSTRAINT uq_prompts_prompt_labels_prompt_label_id_prompt_id
        UNIQUE (prompt_label_id, prompt_id),
    CONSTRAINT fk_prompts_prompt_labels_prompt_id_prompts
        FOREIGN KEY (prompt_id)
        REFERENCES prompts (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_prompts_prompt_labels_prompt_label_id_prompt_labels
        FOREIGN KEY (prompt_label_id)
        REFERENCES prompt_labels (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_prompts_prompt_labels_prompt_id ON prompts_prompt_labels (prompt_id);


-- Table: token_prices
-- -------------------
CREATE TABLE token_prices (
    id INTEGER NOT NULL,
    model_id INTEGER NOT NULL,
    token_type VARCHAR NOT NULL,
    is_prompt BOOLEAN NOT NULL,
    base_rate FLOAT NOT NULL,
    customization JSON,
    CONSTRAINT pk_token_prices PRIMARY KEY (id),
    CONSTRAINT uq_token_prices_model_id_token_type_is_prompt
        UNIQUE (model_id, token_type, is_prompt),
    CONSTRAINT fk_token_prices_model_id_generative_models
        FOREIGN KEY (model_id)
        REFERENCES generative_models (id)
        ON DELETE CASCADE
);


-- Table: traces
-- -------------
CREATE TABLE traces (
    id INTEGER NOT NULL,
    project_rowid INTEGER NOT NULL,
    trace_id VARCHAR NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    project_session_rowid INTEGER,
    CONSTRAINT pk_traces PRIMARY KEY (id),
    CONSTRAINT uq_traces_trace_id UNIQUE (trace_id),
    CONSTRAINT fk_traces_project_rowid_projects
        FOREIGN KEY (project_rowid)
        REFERENCES projects (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_traces_project_session_rowid_project_sessions
        FOREIGN KEY (project_session_rowid)
        REFERENCES project_sessions (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_traces_project_rowid_start_time ON traces
    (project_rowid, start_time DESC);
CREATE INDEX ix_traces_project_session_rowid ON traces (project_session_rowid);


-- Table: spans
-- ------------
CREATE TABLE spans (
    id INTEGER NOT NULL,
    trace_rowid INTEGER NOT NULL,
    span_id VARCHAR NOT NULL,
    parent_id VARCHAR,
    name VARCHAR NOT NULL,
    span_kind VARCHAR NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    attributes JSONB NOT NULL,
    events JSONB NOT NULL,
    status_code VARCHAR DEFAULT 'UNSET' NOT NULL
        CONSTRAINT "ck_spans_`valid_status`"
        CHECK (status_code IN ('OK', 'ERROR', 'UNSET')),
    status_message VARCHAR NOT NULL,
    cumulative_error_count INTEGER NOT NULL,
    cumulative_llm_token_count_prompt INTEGER NOT NULL,
    cumulative_llm_token_count_completion INTEGER NOT NULL,
    llm_token_count_prompt INTEGER,
    llm_token_count_completion INTEGER,
    CONSTRAINT pk_spans PRIMARY KEY (id),
    CONSTRAINT uq_spans_span_id UNIQUE (span_id),
    CONSTRAINT fk_spans_trace_rowid_traces
        FOREIGN KEY (trace_rowid)
        REFERENCES traces (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_cumulative_llm_token_count_total ON spans
    ((cumulative_llm_token_count_prompt + cumulative_llm_token_count_completion));
CREATE INDEX ix_latency ON spans ((end_time - start_time));
CREATE INDEX ix_spans_parent_id ON spans (parent_id);
CREATE INDEX ix_spans_session_id ON spans (JSON_EXTRACT(attributes, '$."session"."id"'))
    WHERE JSON_EXTRACT(attributes, '$."session"."id"') IS NOT NULL;
CREATE INDEX ix_spans_start_time ON spans (start_time);
CREATE INDEX ix_spans_trace_rowid ON spans (trace_rowid);
CREATE INDEX ix_spans_user_id ON spans (JSON_EXTRACT(attributes, '$."user"."id"'))
    WHERE JSON_EXTRACT(attributes, '$."user"."id"') IS NOT NULL;


-- Table: span_costs
-- -----------------
CREATE TABLE span_costs (
    id INTEGER NOT NULL,
    span_rowid INTEGER NOT NULL,
    trace_rowid INTEGER NOT NULL,
    model_id INTEGER,
    span_start_time TIMESTAMP NOT NULL,
    total_cost FLOAT,
    total_tokens FLOAT,
    prompt_cost FLOAT,
    prompt_tokens FLOAT,
    completion_cost FLOAT,
    completion_tokens FLOAT,
    CONSTRAINT pk_span_costs PRIMARY KEY (id),
    CONSTRAINT fk_span_costs_model_id_generative_models
        FOREIGN KEY (model_id)
        REFERENCES generative_models (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_span_costs_span_rowid_spans
        FOREIGN KEY (span_rowid)
        REFERENCES spans (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_span_costs_trace_rowid_traces
        FOREIGN KEY (trace_rowid)
        REFERENCES traces (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_span_costs_model_id_span_start_time ON span_costs
    (model_id, span_start_time);
CREATE INDEX ix_span_costs_span_rowid ON span_costs (span_rowid);
CREATE INDEX ix_span_costs_span_start_time ON span_costs (span_start_time);
CREATE INDEX ix_span_costs_trace_rowid ON span_costs (trace_rowid);


-- Table: span_cost_details
-- ------------------------
CREATE TABLE span_cost_details (
    id INTEGER NOT NULL,
    span_cost_id INTEGER NOT NULL,
    token_type VARCHAR NOT NULL,
    is_prompt BOOLEAN NOT NULL,
    cost FLOAT,
    tokens FLOAT,
    cost_per_token FLOAT,
    CONSTRAINT pk_span_cost_details PRIMARY KEY (id),
    CONSTRAINT uq_span_cost_details_span_cost_id_token_type_is_prompt
        UNIQUE (span_cost_id, token_type, is_prompt),
    CONSTRAINT fk_span_cost_details_span_cost_id_span_costs
        FOREIGN KEY (span_cost_id)
        REFERENCES span_costs (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_span_cost_details_token_type ON span_cost_details (token_type);


-- Table: user_roles
-- -----------------
CREATE TABLE user_roles (
    id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_user_roles_name ON user_roles (name);


-- Table: users
-- ------------
CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user_role_id INTEGER NOT NULL,
    username VARCHAR NOT NULL,
    email VARCHAR,
    profile_picture_url VARCHAR,
    password_hash BLOB,
    password_salt BLOB,
    reset_password BOOLEAN NOT NULL,
    oauth2_client_id VARCHAR,
    oauth2_user_id VARCHAR,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    auth_method VARCHAR NOT NULL,
    ldap_unique_id VARCHAR,
    CONSTRAINT "ck_users_`ldap_auth_valid`"
        CHECK (
            auth_method != 'LDAP'
            OR (
                oauth2_client_id IS NULL
                AND oauth2_user_id IS NULL
                AND (email IS NOT NULL OR ldap_unique_id IS NOT NULL)
            )
        ),
    CONSTRAINT "ck_users_`local_auth_has_password_no_oauth`"
        CHECK (
            auth_method != 'LOCAL'
            OR (
                password_hash IS NOT NULL
                AND password_salt IS NOT NULL
                AND oauth2_client_id IS NULL
                AND oauth2_user_id IS NULL
                AND ldap_unique_id IS NULL
            )
        ),
    CONSTRAINT "ck_users_`non_ldap_auth_has_email`"
        CHECK (auth_method = 'LDAP' OR email IS NOT NULL),
    CONSTRAINT "ck_users_`non_local_auth_has_no_password`"
        CHECK (auth_method = 'LOCAL' OR (password_hash IS NULL AND password_salt IS NULL)),
    CONSTRAINT "ck_users_`oauth2_auth_no_ldap_fields`"
        CHECK (auth_method != 'OAUTH2' OR ldap_unique_id IS NULL),
    CONSTRAINT "ck_users_`valid_auth_method`"
        CHECK (auth_method IN ('LOCAL', 'OAUTH2', 'LDAP')),
    CONSTRAINT fk_users_user_role_id_user_roles
        FOREIGN KEY (user_role_id)
        REFERENCES user_roles (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_users_email ON users (email);
CREATE UNIQUE INDEX ix_users_ldap_unique_id ON users (ldap_unique_id)
    WHERE auth_method = 'LDAP' AND ldap_unique_id IS NOT NULL;
CREATE UNIQUE INDEX ix_users_oauth2_unique ON users (oauth2_client_id, oauth2_user_id)
    WHERE auth_method = 'OAUTH2';
CREATE INDEX ix_users_user_role_id ON users (user_role_id);
CREATE UNIQUE INDEX ix_users_username ON users (username);


-- Table: api_keys
-- ---------------
CREATE TABLE api_keys (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    name VARCHAR NOT NULL,
    description VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    scopes JSONB,
    audience JSONB,
    CONSTRAINT fk_api_keys_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_api_keys_expires_at ON api_keys (expires_at);
CREATE INDEX ix_api_keys_user_id ON api_keys (user_id);


-- Table: dataset_labels
-- ---------------------
CREATE TABLE dataset_labels (
    id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    color VARCHAR NOT NULL,
    user_id INTEGER,
    CONSTRAINT pk_dataset_labels PRIMARY KEY (id),
    CONSTRAINT uq_dataset_labels_name UNIQUE (name),
    CONSTRAINT fk_dataset_labels_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_dataset_labels_user_id ON dataset_labels (user_id);


-- Table: dataset_splits
-- ---------------------
CREATE TABLE dataset_splits (
    id INTEGER NOT NULL,
    user_id INTEGER,
    name VARCHAR NOT NULL,
    description VARCHAR,
    color VARCHAR NOT NULL,
    metadata JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_dataset_splits PRIMARY KEY (id),
    CONSTRAINT uq_dataset_splits_name UNIQUE (name),
    CONSTRAINT fk_dataset_splits_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_dataset_splits_user_id ON dataset_splits (user_id);


-- Table: datasets
-- ---------------
CREATE TABLE datasets (
    id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    metadata JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    user_id INTEGER,
    CONSTRAINT pk_datasets PRIMARY KEY (id),
    CONSTRAINT uq_datasets_name UNIQUE (name),
    CONSTRAINT fk_datasets_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_datasets_user_id ON datasets (user_id);


-- Table: dataset_examples
-- -----------------------
CREATE TABLE dataset_examples (
    id INTEGER NOT NULL,
    dataset_id INTEGER NOT NULL,
    span_rowid INTEGER,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    external_id VARCHAR,
    CONSTRAINT pk_dataset_examples PRIMARY KEY (id),
    CONSTRAINT uq_dataset_examples_dataset_id_external_id
        UNIQUE (dataset_id, external_id),
    CONSTRAINT fk_dataset_examples_dataset_id_datasets
        FOREIGN KEY (dataset_id)
        REFERENCES datasets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_dataset_examples_span_rowid_spans
        FOREIGN KEY (span_rowid)
        REFERENCES spans (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_dataset_examples_span_rowid ON dataset_examples (span_rowid);


-- Table: dataset_splits_dataset_examples
-- --------------------------------------
CREATE TABLE dataset_splits_dataset_examples (
    dataset_split_id INTEGER NOT NULL,
    dataset_example_id INTEGER NOT NULL,
    CONSTRAINT pk_dataset_splits_dataset_examples
        PRIMARY KEY (dataset_split_id, dataset_example_id),
    CONSTRAINT fk_dataset_splits_dataset_examples_dataset_example_id_dataset_examples
        FOREIGN KEY (dataset_example_id)
        REFERENCES dataset_examples (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_dataset_splits_dataset_examples_dataset_split_id_dataset_splits
        FOREIGN KEY (dataset_split_id)
        REFERENCES dataset_splits (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_dataset_splits_dataset_examples_dataset_example_id ON dataset_splits_dataset_examples
    (dataset_example_id);


-- Table: dataset_versions
-- -----------------------
CREATE TABLE dataset_versions (
    id INTEGER NOT NULL,
    dataset_id INTEGER NOT NULL,
    description VARCHAR,
    metadata JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    user_id INTEGER,
    CONSTRAINT pk_dataset_versions PRIMARY KEY (id),
    CONSTRAINT fk_dataset_versions_dataset_id_datasets
        FOREIGN KEY (dataset_id)
        REFERENCES datasets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_dataset_versions_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_dataset_versions_dataset_id ON dataset_versions (dataset_id);
CREATE INDEX ix_dataset_versions_user_id ON dataset_versions (user_id);


-- Table: dataset_example_revisions
-- --------------------------------
CREATE TABLE dataset_example_revisions (
    id INTEGER NOT NULL,
    dataset_example_id INTEGER NOT NULL,
    dataset_version_id INTEGER NOT NULL,
    input JSONB NOT NULL,
    output JSONB NOT NULL,
    metadata JSONB NOT NULL,
    revision_kind VARCHAR NOT NULL
        CONSTRAINT "ck_dataset_example_revisions_`valid_revision_kind`"
        CHECK (revision_kind IN ('CREATE', 'PATCH', 'DELETE')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    content_hash BLOB,
    CONSTRAINT pk_dataset_example_revisions PRIMARY KEY (id),
    CONSTRAINT uq_dataset_example_revisions_dataset_example_id_dataset_version_id
        UNIQUE (dataset_example_id, dataset_version_id),
    CONSTRAINT fk_dataset_example_revisions_dataset_example_id_dataset_examples
        FOREIGN KEY (dataset_example_id)
        REFERENCES dataset_examples (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_dataset_example_revisions_dataset_version_id_dataset_versions
        FOREIGN KEY (dataset_version_id)
        REFERENCES dataset_versions (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_dataset_example_revisions_content_hash ON dataset_example_revisions
    (content_hash);
CREATE INDEX ix_dataset_example_revisions_dataset_version_id ON dataset_example_revisions
    (dataset_version_id);


-- Table: datasets_dataset_labels
-- ------------------------------
CREATE TABLE datasets_dataset_labels (
    dataset_id INTEGER NOT NULL,
    dataset_label_id INTEGER NOT NULL,
    CONSTRAINT pk_datasets_dataset_labels PRIMARY KEY (dataset_id, dataset_label_id),
    CONSTRAINT fk_datasets_dataset_labels_dataset_id_datasets
        FOREIGN KEY (dataset_id)
        REFERENCES datasets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_datasets_dataset_labels_dataset_label_id_dataset_labels
        FOREIGN KEY (dataset_label_id)
        REFERENCES dataset_labels (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_datasets_dataset_labels_dataset_label_id ON datasets_dataset_labels
    (dataset_label_id);


-- Table: document_annotations
-- ---------------------------
CREATE TABLE document_annotations (
    id INTEGER NOT NULL,
    span_rowid INTEGER NOT NULL,
    document_position INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    label VARCHAR,
    score FLOAT,
    explanation VARCHAR,
    metadata JSONB NOT NULL,
    annotator_kind VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    user_id INTEGER,
    identifier VARCHAR DEFAULT ('') NOT NULL,
    source VARCHAR NOT NULL,
    CONSTRAINT pk_document_annotations PRIMARY KEY (id),
    CONSTRAINT uq_document_annotations_name_span_rowid_document_pos_identifier
        UNIQUE (name, span_rowid, document_position, identifier),
    CONSTRAINT "ck_document_annotations_`valid_annotator_kind`"
        CHECK (annotator_kind IN ('LLM', 'CODE', 'HUMAN')),
    CONSTRAINT "ck_document_annotations_`valid_source`" CHECK (source IN ('API', 'APP')),
    CONSTRAINT fk_document_annotations_span_rowid_spans
        FOREIGN KEY (span_rowid)
        REFERENCES spans (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_document_annotations_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_document_annotations_span_rowid ON document_annotations (span_rowid);
CREATE INDEX ix_document_annotations_user_id ON document_annotations (user_id);


-- Table: evaluators
-- -----------------
CREATE TABLE evaluators (
    id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    metadata JSONB NOT NULL,
    kind VARCHAR NOT NULL
        CONSTRAINT "ck_evaluators_`valid_evaluator_kind`"
        CHECK (kind IN ('LLM', 'CODE', 'BUILTIN')),
    user_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_evaluators PRIMARY KEY (id),
    CONSTRAINT uq_evaluators_kind_id UNIQUE (kind, id),
    CONSTRAINT uq_evaluators_name UNIQUE (name),
    CONSTRAINT fk_evaluators_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_evaluators_user_id ON evaluators (user_id);


-- Table: builtin_evaluators
-- -------------------------
CREATE TABLE builtin_evaluators (
    id INTEGER NOT NULL,
    kind VARCHAR DEFAULT 'BUILTIN' NOT NULL
        CONSTRAINT "ck_builtin_evaluators_`valid_evaluator_kind`"
        CHECK (kind = 'BUILTIN'),
    "key" VARCHAR NOT NULL,
    input_schema JSONB NOT NULL,
    output_configs JSONB NOT NULL,
    synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_builtin_evaluators PRIMARY KEY (id),
    CONSTRAINT uq_builtin_evaluators_key UNIQUE ("key"),
    CONSTRAINT fk_builtin_evaluators_kind_evaluators
        FOREIGN KEY (kind, id)
        REFERENCES evaluators (kind, id)
        ON DELETE CASCADE
);


-- Table: dataset_evaluators
-- -------------------------
CREATE TABLE dataset_evaluators (
    id INTEGER NOT NULL,
    dataset_id INTEGER NOT NULL,
    evaluator_id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    output_configs JSONB NOT NULL,
    input_mapping JSONB NOT NULL,
    user_id INTEGER,
    project_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_dataset_evaluators PRIMARY KEY (id),
    CONSTRAINT uq_dataset_evaluators_dataset_id_name UNIQUE (dataset_id, name),
    CONSTRAINT fk_dataset_evaluators_dataset_id_datasets
        FOREIGN KEY (dataset_id)
        REFERENCES datasets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_dataset_evaluators_evaluator_id_evaluators
        FOREIGN KEY (evaluator_id)
        REFERENCES evaluators (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_dataset_evaluators_project_id_projects
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_dataset_evaluators_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_dataset_evaluators_evaluator_id ON dataset_evaluators (evaluator_id);
CREATE INDEX ix_dataset_evaluators_project_id ON dataset_evaluators (project_id);


-- Table: experiments
-- ------------------
CREATE TABLE experiments (
    id INTEGER NOT NULL,
    dataset_id INTEGER NOT NULL,
    dataset_version_id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    repetitions INTEGER NOT NULL,
    metadata JSONB NOT NULL,
    project_name VARCHAR,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    user_id INTEGER,
    is_ephemeral BOOLEAN DEFAULT 0 NOT NULL,
    CONSTRAINT pk_experiments PRIMARY KEY (id),
    CONSTRAINT fk_experiments_dataset_id_datasets
        FOREIGN KEY (dataset_id)
        REFERENCES datasets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_experiments_dataset_version_id_dataset_versions
        FOREIGN KEY (dataset_version_id)
        REFERENCES dataset_versions (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_experiments_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_experiments_dataset_id ON experiments (dataset_id);
CREATE INDEX ix_experiments_dataset_version_id ON experiments (dataset_version_id);
CREATE INDEX ix_experiments_ephemeral_updated_at ON experiments (updated_at)
    WHERE is_ephemeral IS TRUE;
CREATE INDEX ix_experiments_project_name ON experiments (project_name);
CREATE INDEX ix_experiments_user_id ON experiments (user_id);


-- Table: experiment_jobs
-- ----------------------
CREATE TABLE experiment_jobs (
    id INTEGER NOT NULL,
    type VARCHAR NOT NULL
        CONSTRAINT "ck_experiment_jobs_`valid_type`"
        CHECK (type IN ('PROMPT', 'EVAL_ONLY')),
    status VARCHAR DEFAULT 'STOPPED' NOT NULL
        CONSTRAINT "ck_experiment_jobs_`valid_experiment_status`"
        CHECK (status IN ('RUNNING', 'COMPLETED', 'STOPPED', 'ERROR')),
    claimed_at TIMESTAMP,
    claimed_by VARCHAR,
    cooldown_until TIMESTAMP,
    max_concurrency INTEGER DEFAULT '10' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_experiment_jobs PRIMARY KEY (id),
    CONSTRAINT uq_experiment_jobs_type_id UNIQUE (type, id),
    CONSTRAINT fk_experiment_jobs_id_experiments
        FOREIGN KEY (id)
        REFERENCES experiments (id)
        ON DELETE CASCADE
);


-- Table: experiment_dataset_evaluators
-- ------------------------------------
CREATE TABLE experiment_dataset_evaluators (
    experiment_id INTEGER NOT NULL,
    dataset_evaluator_id INTEGER NOT NULL,
    CONSTRAINT pk_experiment_dataset_evaluators
        PRIMARY KEY (experiment_id, dataset_evaluator_id),
    CONSTRAINT fk_experiment_dataset_evaluators_dataset_evaluator_id_dataset_evaluators
        FOREIGN KEY (dataset_evaluator_id)
        REFERENCES dataset_evaluators (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_experiment_dataset_evaluators_experiment_id_experiment_jobs
        FOREIGN KEY (experiment_id)
        REFERENCES experiment_jobs (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_experiment_dataset_evaluators_dataset_evaluator_id ON experiment_dataset_evaluators
    (dataset_evaluator_id);


-- Table: experiment_logs
-- ----------------------
CREATE TABLE experiment_logs (
    id INTEGER NOT NULL,
    experiment_id INTEGER NOT NULL,
    occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    category VARCHAR NOT NULL
        CONSTRAINT "ck_experiment_logs_`valid_event_category`"
        CHECK (category IN ('TASK', 'EVAL', 'EXPERIMENT')),
    level VARCHAR NOT NULL
        CONSTRAINT "ck_experiment_logs_`valid_event_level`"
        CHECK (level IN ('ERROR', 'WARN', 'INFO')),
    message VARCHAR NOT NULL,
    detail JSONB,
    CONSTRAINT pk_experiment_logs PRIMARY KEY (id),
    CONSTRAINT uq_experiment_logs_category_id UNIQUE (category, id),
    CONSTRAINT fk_experiment_logs_experiment_id_experiment_jobs
        FOREIGN KEY (experiment_id)
        REFERENCES experiment_jobs (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_experiment_logs_experiment_id ON experiment_logs (experiment_id);
CREATE INDEX ix_experiment_logs_experiment_id_occurred_at_errors ON experiment_logs
    (experiment_id, occurred_at DESC)
    WHERE level = 'ERROR';


-- Table: experiment_runs
-- ----------------------
CREATE TABLE experiment_runs (
    id INTEGER NOT NULL,
    experiment_id INTEGER NOT NULL,
    dataset_example_id INTEGER NOT NULL,
    repetition_number INTEGER NOT NULL,
    trace_id VARCHAR,
    output JSONB NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    prompt_token_count INTEGER,
    completion_token_count INTEGER,
    error VARCHAR,
    CONSTRAINT pk_experiment_runs PRIMARY KEY (id),
    CONSTRAINT uq_experiment_runs_experiment_id_dataset_example_id_repetition_number
        UNIQUE (experiment_id, dataset_example_id, repetition_number),
    CONSTRAINT fk_experiment_runs_dataset_example_id_dataset_examples
        FOREIGN KEY (dataset_example_id)
        REFERENCES dataset_examples (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_experiment_runs_experiment_id_experiments
        FOREIGN KEY (experiment_id)
        REFERENCES experiments (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_experiment_runs_dataset_example_id ON experiment_runs
    (dataset_example_id);


-- Table: experiment_eval_logs
-- ---------------------------
CREATE TABLE experiment_eval_logs (
    id INTEGER NOT NULL,
    category VARCHAR DEFAULT 'EVAL' NOT NULL
        CONSTRAINT "ck_experiment_eval_logs_`valid_category`"
        CHECK (category = 'EVAL'),
    experiment_run_id INTEGER NOT NULL,
    dataset_evaluator_id INTEGER NOT NULL,
    CONSTRAINT pk_experiment_eval_logs PRIMARY KEY (id),
    CONSTRAINT fk_experiment_eval_logs_category_experiment_logs
        FOREIGN KEY (category, id)
        REFERENCES experiment_logs (category, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_experiment_eval_logs_dataset_evaluator_id_dataset_evaluators
        FOREIGN KEY (dataset_evaluator_id)
        REFERENCES dataset_evaluators (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_experiment_eval_logs_experiment_run_id_experiment_runs
        FOREIGN KEY (experiment_run_id)
        REFERENCES experiment_runs (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_experiment_eval_logs_dataset_evaluator_id ON experiment_eval_logs
    (dataset_evaluator_id);
CREATE INDEX ix_experiment_eval_logs_experiment_run_id ON experiment_eval_logs
    (experiment_run_id);


-- Table: experiment_run_annotations
-- ---------------------------------
CREATE TABLE experiment_run_annotations (
    id INTEGER NOT NULL,
    experiment_run_id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    annotator_kind VARCHAR NOT NULL
        CONSTRAINT "ck_experiment_run_annotations_`valid_annotator_kind`"
        CHECK (annotator_kind IN ('LLM', 'CODE', 'HUMAN')),
    label VARCHAR,
    score FLOAT,
    explanation VARCHAR,
    trace_id VARCHAR,
    error VARCHAR,
    metadata JSONB NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    CONSTRAINT pk_experiment_run_annotations PRIMARY KEY (id),
    CONSTRAINT uq_experiment_run_annotations_experiment_run_id_name
        UNIQUE (experiment_run_id, name),
    CONSTRAINT fk_experiment_run_annotations_experiment_run_id_experiment_runs
        FOREIGN KEY (experiment_run_id)
        REFERENCES experiment_runs (id)
        ON DELETE CASCADE
);


-- Table: experiment_tags
-- ----------------------
CREATE TABLE experiment_tags (
    id INTEGER NOT NULL,
    experiment_id INTEGER NOT NULL,
    dataset_id INTEGER NOT NULL,
    user_id INTEGER,
    name VARCHAR NOT NULL,
    description VARCHAR,
    CONSTRAINT pk_experiment_tags PRIMARY KEY (id),
    CONSTRAINT uq_experiment_tags_dataset_id_name UNIQUE (dataset_id, name),
    CONSTRAINT fk_experiment_tags_dataset_id_datasets
        FOREIGN KEY (dataset_id)
        REFERENCES datasets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_experiment_tags_experiment_id_experiments
        FOREIGN KEY (experiment_id)
        REFERENCES experiments (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_experiment_tags_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_experiment_tags_experiment_id ON experiment_tags (experiment_id);
CREATE INDEX ix_experiment_tags_user_id ON experiment_tags (user_id);


-- Table: experiment_task_logs
-- ---------------------------
CREATE TABLE experiment_task_logs (
    id INTEGER NOT NULL,
    category VARCHAR DEFAULT 'TASK' NOT NULL
        CONSTRAINT "ck_experiment_task_logs_`valid_category`"
        CHECK (category = 'TASK'),
    dataset_example_id INTEGER NOT NULL,
    repetition_number INTEGER NOT NULL,
    CONSTRAINT pk_experiment_task_logs PRIMARY KEY (id),
    CONSTRAINT fk_experiment_task_logs_category_experiment_logs
        FOREIGN KEY (category, id)
        REFERENCES experiment_logs (category, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_experiment_task_logs_dataset_example_id_dataset_examples
        FOREIGN KEY (dataset_example_id)
        REFERENCES dataset_examples (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_experiment_task_logs_dataset_example_id ON experiment_task_logs
    (dataset_example_id);


-- Table: experiments_dataset_examples
-- -----------------------------------
CREATE TABLE experiments_dataset_examples (
    experiment_id INTEGER NOT NULL,
    dataset_example_id INTEGER NOT NULL,
    dataset_example_revision_id INTEGER NOT NULL,
    CONSTRAINT pk_experiments_dataset_examples
        PRIMARY KEY (experiment_id, dataset_example_id),
    CONSTRAINT fk_experiments_dataset_examples_dataset_example_id_dataset_examples
        FOREIGN KEY (dataset_example_id)
        REFERENCES dataset_examples (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_experiments_dataset_examples_dataset_example_revision_id_dataset_example_revisions
        FOREIGN KEY (dataset_example_revision_id)
        REFERENCES dataset_example_revisions (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_experiments_dataset_examples_experiment_id_experiments
        FOREIGN KEY (experiment_id)
        REFERENCES experiments (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_experiments_dataset_examples_dataset_example_id ON experiments_dataset_examples
    (dataset_example_id);
CREATE INDEX ix_experiments_dataset_examples_dataset_example_revision_id ON experiments_dataset_examples
    (dataset_example_revision_id);


-- Table: experiments_dataset_splits
-- ---------------------------------
CREATE TABLE experiments_dataset_splits (
    experiment_id INTEGER NOT NULL,
    dataset_split_id INTEGER NOT NULL,
    CONSTRAINT pk_experiments_dataset_splits
        PRIMARY KEY (experiment_id, dataset_split_id),
    CONSTRAINT fk_experiments_dataset_splits_dataset_split_id_dataset_splits
        FOREIGN KEY (dataset_split_id)
        REFERENCES dataset_splits (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_experiments_dataset_splits_experiment_id_experiments
        FOREIGN KEY (experiment_id)
        REFERENCES experiments (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_experiments_dataset_splits_dataset_split_id ON experiments_dataset_splits
    (dataset_split_id);


-- Table: generative_model_custom_providers
-- ----------------------------------------
CREATE TABLE generative_model_custom_providers (
    id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    provider VARCHAR NOT NULL,
    sdk VARCHAR NOT NULL,
    config BLOB NOT NULL,
    user_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_generative_model_custom_providers PRIMARY KEY (id),
    CONSTRAINT uq_generative_model_custom_providers_name UNIQUE (name),
    CONSTRAINT fk_generative_model_custom_providers_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);


-- Table: oauth2_authorization_codes
-- ---------------------------------
CREATE TABLE oauth2_authorization_codes (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    code_hash VARCHAR NOT NULL,
    user_id INTEGER NOT NULL,
    oauth2_client_id INTEGER NOT NULL,
    redirect_uri VARCHAR NOT NULL,
    code_challenge VARCHAR NOT NULL,
    code_challenge_method VARCHAR NOT NULL,
    scopes JSONB,
    resource VARCHAR,
    audience JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_oauth2_authorization_codes_oauth2_client_id_oauth2_clients
        FOREIGN KEY (oauth2_client_id)
        REFERENCES oauth2_clients (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_oauth2_authorization_codes_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_oauth2_authorization_codes_code_hash ON oauth2_authorization_codes
    (code_hash);
CREATE INDEX ix_oauth2_authorization_codes_expires_at ON oauth2_authorization_codes
    (expires_at);


-- Table: oauth2_grants
-- --------------------
CREATE TABLE oauth2_grants (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    oauth2_client_id INTEGER NOT NULL,
    scopes JSONB,
    audience JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    last_used_at TIMESTAMP,
    revoked_at TIMESTAMP,
    CONSTRAINT fk_oauth2_grants_oauth2_client_id_oauth2_clients
        FOREIGN KEY (oauth2_client_id)
        REFERENCES oauth2_clients (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_oauth2_grants_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_oauth2_grants_oauth2_client_id ON oauth2_grants (oauth2_client_id);
CREATE INDEX ix_oauth2_grants_user_id ON oauth2_grants (user_id);


-- Table: password_reset_tokens
-- ----------------------------
CREATE TABLE password_reset_tokens (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_password_reset_tokens_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_password_reset_tokens_expires_at ON password_reset_tokens (expires_at);
CREATE UNIQUE INDEX ix_password_reset_tokens_user_id ON password_reset_tokens (user_id);


-- Table: project_session_annotations
-- ----------------------------------
CREATE TABLE project_session_annotations (
    id INTEGER NOT NULL,
    project_session_id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    label VARCHAR,
    score FLOAT,
    explanation VARCHAR,
    metadata JSONB NOT NULL,
    annotator_kind VARCHAR NOT NULL
        CONSTRAINT "ck_project_session_annotations_`valid_annotator_kind`"
        CHECK (annotator_kind IN ('LLM', 'CODE', 'HUMAN')),
    user_id INTEGER,
    identifier VARCHAR DEFAULT '' NOT NULL,
    source VARCHAR NOT NULL
        CONSTRAINT "ck_project_session_annotations_`valid_source`"
        CHECK (source IN ('API', 'APP')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_project_session_annotations PRIMARY KEY (id),
    CONSTRAINT uq_project_session_annotations_name_project_session_id_identifier
        UNIQUE (name, project_session_id, identifier),
    CONSTRAINT fk_project_session_annotations_project_session_id_project_sessions
        FOREIGN KEY (project_session_id)
        REFERENCES project_sessions (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_project_session_annotations_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_project_session_annotations_project_session_id ON project_session_annotations
    (project_session_id);
CREATE INDEX ix_project_session_annotations_user_id ON project_session_annotations
    (user_id);


-- Table: prompt_versions
-- ----------------------
CREATE TABLE prompt_versions (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    prompt_id INTEGER NOT NULL,
    description VARCHAR,
    user_id INTEGER,
    template_type VARCHAR NOT NULL,
    template_format VARCHAR NOT NULL,
    template JSONB NOT NULL,
    invocation_parameters JSONB NOT NULL,
    tools JSON,
    response_format JSON,
    model_provider VARCHAR NOT NULL,
    model_name VARCHAR NOT NULL,
    metadata JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    custom_provider_id INTEGER,
    CONSTRAINT "ck_prompt_versions_`template_format`"
        CHECK (template_format IN ('F_STRING', 'MUSTACHE', 'NONE')),
    CONSTRAINT "ck_prompt_versions_`template_type`"
        CHECK (template_type IN ('CHAT', 'STR')),
    CONSTRAINT fk_prompt_versions_custom_provider_id_generative_model_custom_providers
        FOREIGN KEY (custom_provider_id)
        REFERENCES generative_model_custom_providers (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_prompt_versions_prompt_id_prompts
        FOREIGN KEY (prompt_id)
        REFERENCES prompts (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_prompt_versions_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_prompt_versions_custom_provider_id ON prompt_versions
    (custom_provider_id);
CREATE INDEX ix_prompt_versions_prompt_id ON prompt_versions (prompt_id);
CREATE INDEX ix_prompt_versions_user_id ON prompt_versions (user_id);


-- Table: experiment_prompt_tasks
-- ------------------------------
CREATE TABLE experiment_prompt_tasks (
    id INTEGER NOT NULL,
    type VARCHAR DEFAULT 'PROMPT' NOT NULL
        CONSTRAINT "ck_experiment_prompt_tasks_`valid_type`"
        CHECK (type = 'PROMPT'),
    prompt_version_id INTEGER,
    model_provider VARCHAR NOT NULL,
    model_name VARCHAR NOT NULL,
    custom_provider_id INTEGER,
    template_type VARCHAR NOT NULL,
    template_format VARCHAR NOT NULL,
    template JSONB NOT NULL,
    tools JSONB,
    response_format JSONB,
    invocation_parameters JSONB DEFAULT '{}' NOT NULL,
    connection JSONB,
    playground_config JSONB,
    stream_model_output BOOLEAN DEFAULT '1' NOT NULL,
    CONSTRAINT pk_experiment_prompt_tasks PRIMARY KEY (id),
    CONSTRAINT "ck_experiment_prompt_tasks_`custom_provider_or_connection`"
        CHECK (NOT (custom_provider_id IS NOT NULL AND connection IS NOT NULL)),
    CONSTRAINT fk_experiment_prompt_tasks_custom_provider_id_generative_model_custom_providers
        FOREIGN KEY (custom_provider_id)
        REFERENCES generative_model_custom_providers (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_experiment_prompt_tasks_prompt_version_id_prompt_versions
        FOREIGN KEY (prompt_version_id)
        REFERENCES prompt_versions (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_experiment_prompt_tasks_type_experiment_jobs
        FOREIGN KEY (type, id)
        REFERENCES experiment_jobs (type, id)
        ON DELETE CASCADE
);


-- Table: prompt_version_tags
-- --------------------------
CREATE TABLE prompt_version_tags (
    id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    prompt_id INTEGER NOT NULL,
    prompt_version_id INTEGER NOT NULL,
    user_id INTEGER,
    CONSTRAINT pk_prompt_version_tags PRIMARY KEY (id),
    CONSTRAINT uq_prompt_version_tags_name_prompt_id UNIQUE (name, prompt_id),
    CONSTRAINT fk_prompt_version_tags_prompt_id_prompts
        FOREIGN KEY (prompt_id)
        REFERENCES prompts (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_prompt_version_tags_prompt_version_id_prompt_versions
        FOREIGN KEY (prompt_version_id)
        REFERENCES prompt_versions (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_prompt_version_tags_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_prompt_version_tags_prompt_id ON prompt_version_tags (prompt_id);
CREATE INDEX ix_prompt_version_tags_prompt_version_id ON prompt_version_tags
    (prompt_version_id);
CREATE INDEX ix_prompt_version_tags_user_id ON prompt_version_tags (user_id);


-- Table: llm_evaluators
-- ---------------------
CREATE TABLE llm_evaluators (
    id INTEGER NOT NULL,
    kind VARCHAR DEFAULT 'LLM' NOT NULL
        CONSTRAINT "ck_llm_evaluators_`valid_evaluator_kind`"
        CHECK (kind = 'LLM'),
    prompt_id INTEGER NOT NULL,
    prompt_version_tag_id INTEGER,
    output_configs JSONB NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_llm_evaluators PRIMARY KEY (id),
    CONSTRAINT fk_llm_evaluators_kind_evaluators
        FOREIGN KEY (kind, id)
        REFERENCES evaluators (kind, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_llm_evaluators_prompt_id_prompts
        FOREIGN KEY (prompt_id)
        REFERENCES prompts (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_llm_evaluators_prompt_version_tag_id_prompt_version_tags
        FOREIGN KEY (prompt_version_tag_id)
        REFERENCES prompt_version_tags (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_llm_evaluators_prompt_id ON llm_evaluators (prompt_id);
CREATE INDEX ix_llm_evaluators_prompt_version_tag_id ON llm_evaluators
    (prompt_version_tag_id);


-- Table: refresh_tokens
-- ---------------------
CREATE TABLE refresh_tokens (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    oauth2_grant_id INTEGER,
    scopes JSONB,
    audience JSONB,
    consumed_at TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_oauth2_grant_id_oauth2_grants
        FOREIGN KEY (oauth2_grant_id)
        REFERENCES oauth2_grants (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_refresh_tokens_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX ix_refresh_tokens_oauth2_grant_id ON refresh_tokens (oauth2_grant_id);
CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);


-- Table: access_tokens
-- --------------------
CREATE TABLE access_tokens (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    refresh_token_id INTEGER NOT NULL,
    scopes JSONB,
    audience JSONB,
    CONSTRAINT fk_access_tokens_refresh_token_id_refresh_tokens
        FOREIGN KEY (refresh_token_id)
        REFERENCES refresh_tokens (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_access_tokens_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_access_tokens_expires_at ON access_tokens (expires_at);
CREATE UNIQUE INDEX ix_access_tokens_refresh_token_id ON access_tokens
    (refresh_token_id);
CREATE INDEX ix_access_tokens_user_id ON access_tokens (user_id);


-- Table: sandbox_providers
-- ------------------------
CREATE TABLE sandbox_providers (
    backend_type VARCHAR NOT NULL,
    enabled BOOLEAN NOT NULL,
    config JSONB DEFAULT '{}' NOT NULL,
    user_id INTEGER,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_sandbox_providers PRIMARY KEY (backend_type),
    CONSTRAINT fk_sandbox_providers_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_sandbox_providers_user_id ON sandbox_providers (user_id);


-- Table: sandbox_configs
-- ----------------------
CREATE TABLE sandbox_configs (
    id INTEGER NOT NULL,
    backend_type VARCHAR NOT NULL,
    language VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    config JSONB DEFAULT '{}' NOT NULL,
    timeout INTEGER NOT NULL,
    enabled BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id INTEGER,
    CONSTRAINT pk_sandbox_configs PRIMARY KEY (id),
    CONSTRAINT uq_sandbox_configs_backend_type_name UNIQUE (backend_type, name),
    CONSTRAINT uq_sandbox_configs_language_id UNIQUE (language, id),
    CONSTRAINT fk_sandbox_configs_backend_type_sandbox_providers
        FOREIGN KEY (backend_type)
        REFERENCES sandbox_providers (backend_type)
        ON DELETE RESTRICT,
    CONSTRAINT fk_sandbox_configs_language_languages
        FOREIGN KEY (language)
        REFERENCES languages (name)
        ON DELETE RESTRICT,
    CONSTRAINT fk_sandbox_configs_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_sandbox_configs_user_id ON sandbox_configs (user_id);


-- Table: code_evaluators
-- ----------------------
CREATE TABLE code_evaluators (
    id INTEGER NOT NULL,
    kind VARCHAR DEFAULT 'CODE' NOT NULL,
    updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    language VARCHAR NOT NULL,
    input_mapping JSONB DEFAULT '{"literal_mapping": {}, "path_mapping": {}}' NOT NULL,
    output_configs JSONB DEFAULT '[]' NOT NULL,
    sandbox_config_id INTEGER,
    CONSTRAINT pk_code_evaluators PRIMARY KEY (id),
    CONSTRAINT "ck_code_evaluators_`valid_evaluator_kind`" CHECK (kind = 'CODE'),
    CONSTRAINT fk_code_evaluators_kind_evaluators
        FOREIGN KEY (kind, id)
        REFERENCES evaluators (kind, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_code_evaluators_language_languages
        FOREIGN KEY (language)
        REFERENCES languages (name)
        ON DELETE RESTRICT,
    CONSTRAINT fk_code_evaluators_sandbox_config_id_sandbox_configs
        FOREIGN KEY (sandbox_config_id)
        REFERENCES sandbox_configs (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_code_evaluators_sandbox_config_language
        FOREIGN KEY (sandbox_config_id, language)
        REFERENCES sandbox_configs (id, language)
);

CREATE INDEX ix_code_evaluators_language ON code_evaluators (language);
CREATE INDEX ix_code_evaluators_sandbox_config_id ON code_evaluators
    (sandbox_config_id);


-- Table: code_evaluator_code_versions
-- -----------------------------------
CREATE TABLE code_evaluator_code_versions (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    code_evaluator_id INTEGER NOT NULL,
    user_id INTEGER,
    source_code VARCHAR DEFAULT '' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_code_evaluator_code_versions_code_evaluator_id_code_evaluators
        FOREIGN KEY (code_evaluator_id)
        REFERENCES code_evaluators (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_code_evaluator_code_versions_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_code_evaluator_code_versions_code_evaluator_id_id ON code_evaluator_code_versions
    (code_evaluator_id, id);
CREATE INDEX ix_code_evaluator_code_versions_user_id ON code_evaluator_code_versions
    (user_id);


-- Table: secrets
-- --------------
CREATE TABLE secrets (
    "key" VARCHAR NOT NULL,
    value BLOB NOT NULL,
    user_id INTEGER,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_secrets PRIMARY KEY ("key"),
    CONSTRAINT fk_secrets_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);


-- Table: span_annotations
-- -----------------------
CREATE TABLE span_annotations (
    id INTEGER NOT NULL,
    span_rowid INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    label VARCHAR,
    score FLOAT,
    explanation VARCHAR,
    metadata JSONB NOT NULL,
    annotator_kind VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    user_id INTEGER,
    identifier VARCHAR DEFAULT ('') NOT NULL,
    source VARCHAR NOT NULL,
    CONSTRAINT pk_span_annotations PRIMARY KEY (id),
    CONSTRAINT uq_span_annotations_name_span_rowid_identifier
        UNIQUE (name, span_rowid, identifier),
    CONSTRAINT "ck_span_annotations_`valid_annotator_kind`"
        CHECK (annotator_kind IN ('LLM', 'CODE', 'HUMAN')),
    CONSTRAINT "ck_span_annotations_`valid_source`" CHECK (source IN ('API', 'APP')),
    CONSTRAINT fk_span_annotations_span_rowid_spans
        FOREIGN KEY (span_rowid)
        REFERENCES spans (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_span_annotations_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_span_annotations_span_rowid ON span_annotations (span_rowid);
CREATE INDEX ix_span_annotations_user_id ON span_annotations (user_id);


-- Table: system_settings
-- ----------------------
CREATE TABLE system_settings (
    "key" VARCHAR NOT NULL,
    value JSONB NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INTEGER,
    CONSTRAINT pk_system_settings PRIMARY KEY ("key"),
    CONSTRAINT fk_system_settings_updated_by_users
        FOREIGN KEY (updated_by)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_system_settings_updated_at ON system_settings (updated_at);


-- Table: trace_annotations
-- ------------------------
CREATE TABLE trace_annotations (
    id INTEGER NOT NULL,
    trace_rowid INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    label VARCHAR,
    score FLOAT,
    explanation VARCHAR,
    metadata JSONB NOT NULL,
    annotator_kind VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    user_id INTEGER,
    identifier VARCHAR DEFAULT ('') NOT NULL,
    source VARCHAR NOT NULL,
    CONSTRAINT pk_trace_annotations PRIMARY KEY (id),
    CONSTRAINT uq_trace_annotations_name_trace_rowid_identifier
        UNIQUE (name, trace_rowid, identifier),
    CONSTRAINT "ck_trace_annotations_`valid_annotator_kind`"
        CHECK (annotator_kind IN ('LLM', 'CODE', 'HUMAN')),
    CONSTRAINT "ck_trace_annotations_`valid_source`" CHECK (source IN ('API', 'APP')),
    CONSTRAINT fk_trace_annotations_trace_rowid_traces
        FOREIGN KEY (trace_rowid)
        REFERENCES traces (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_trace_annotations_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_trace_annotations_trace_rowid ON trace_annotations (trace_rowid);
CREATE INDEX ix_trace_annotations_user_id ON trace_annotations (user_id);
