name: "Chromatic"

on:
  pull_request:
    paths:
      - "app/src/**"
      - "app/stories/**"
      - "app/package.json"
      - "app/pnpm-lock.yaml"
      - "app/.storybook/**"
      - "app/vite.config.*"
      - "app/webpack.config.*"
      - "app/tsconfig.*"
      - "app/tailwind.config.*"
      - "app/postcss.config.*"
      - "app/.eslintrc.*"
      - "app/.prettierrc.*"
      - "app/jest.config.*"
      - "app/cypress.config.*"
      - "app/playwright.config.*"

permissions:
  contents: read

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - uses: pnpm/action-setup@v4
        with:
          version: 10.2.0
      - name: Install dependencies
        working-directory: ./app
        run: pnpm install --frozen-lockfile
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./app
