name: Lint PR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - edited

concurrency:
  group: lint-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}