name: Python Cron

on:
  schedule:
    - cron: "*/15 15-23 * * 1-5"
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: phoenix
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install tox-uv==1.11.3
      - run: tox run-parallel --parallel-no-spinner -e test-integration_tests
      - uses: slackapi/slack-github-action@v1
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": "FAILED Python Integration Test: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
