name: Publish Any Pull Request
permissions:
  contents: write
  pull-requests: write
# TODO: Only publish on pull requests by arize team members
on:
  pull_request:

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      workflow_file: ${{ steps.filter.outputs.workflow_file }}
      phoenix-client: ${{ steps.filter.outputs.phoenix-client }}
      phoenix-mcp: ${{ steps.filter.outputs.phoenix-mcp }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            phoenix-client:
              - 'js/packages/phoenix-client/**'
            phoenix-mcp:
              - 'js/packages/phoenix-mcp/**'
            workflow_file:
              - '.github/workflows/typescript-packages-publish-experimental.yml'

  publish-experimental-packages:
    needs: changes
    if: ${{ needs.changes.outputs.phoenix-client == 'true' || needs.changes.outputs.phoenix-mcp == 'true' || needs.changes.outputs.workflow_file == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # workaround for broken corepack https://github.com/nodejs/corepack/issues/612
      - run: |
          npm i -g corepack@latest
          corepack enable
        working-directory: ./js
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./js
        run: pnpm install

      - name: Build
        working-directory: ./js
        run: pnpm -r build

      - name: Publish
        working-directory: ./js
        run: pnpx pkg-pr-new publish ./packages/phoenix-client ./packages/phoenix-mcp
