name: Publish Any Pull Request
on:
  pull_request:
    paths:
      - "js/**"
      - ".github/workflows/typescript-packages-publish-experimental.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
        working-directory: ./js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: ./js

      - name: Install dependencies
        working-directory: ./js
        run: pnpm install

      - name: Build
        working-directory: ./js
        run: pnpm build

      - name: Publish
        working-directory: ./js
        run: pnpx pkg-pr-new publish ./packages/phoenix-client
